stim = [
  {
    "stem": "koncert",
    "back": 69,
    "front": 510521,
    "log_odds_back": -8.9091,
    "stem_freq": 510590,
    "language": "de",
    "log_odds_adj": -8.8947,
    "transcription": "koncert",
    "trial_type": "pl",
    "target": "koncertok",
    "prompt": "<p>Ez egy koncert. Azok ott koncertok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">koncertok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "koncert",
    "back": 69,
    "front": 510521,
    "log_odds_back": -8.9091,
    "stem_freq": 510590,
    "language": "de",
    "log_odds_adj": -8.8947,
    "transcription": "koncert",
    "trial_type": "dat",
    "target": "koncertnak",
    "prompt": "<p>Ez egy koncert. Elneveztem a kutyámat koncertnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">koncertnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "log_odds_adj": -8.359,
    "transcription": "docenš",
    "trial_type": "pl",
    "target": "docensok",
    "prompt": "<p>Ez egy docens. Azok ott docensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">docensok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "log_odds_adj": -8.359,
    "transcription": "docenš",
    "trial_type": "dat",
    "target": "docensnak",
    "prompt": "<p>Ez egy docens. Elneveztem a kutyámat docensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">docensnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "projekt",
    "back": 193,
    "front": 704053,
    "log_odds_back": -8.2019,
    "stem_freq": 704246,
    "language": "en",
    "log_odds_adj": -8.1968,
    "transcription": "projekt",
    "trial_type": "pl",
    "target": "projektok",
    "prompt": "<p>Ez egy projekt. Azok ott projektok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">projektok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "projekt",
    "back": 193,
    "front": 704053,
    "log_odds_back": -8.2019,
    "stem_freq": 704246,
    "language": "en",
    "log_odds_adj": -8.1968,
    "transcription": "projekt",
    "trial_type": "dat",
    "target": "projektnak",
    "prompt": "<p>Ez egy projekt. Elneveztem a kutyámat projektnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">projektnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szovjet",
    "back": 8,
    "front": 31869,
    "log_odds_back": -8.2899,
    "stem_freq": 31877,
    "language": "ru",
    "log_odds_adj": -8.1722,
    "transcription": "sovjet",
    "trial_type": "pl",
    "target": "szovjetok",
    "prompt": "<p>Ez egy szovjet. Azok ott szovjetok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szovjetok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szovjet",
    "back": 8,
    "front": 31869,
    "log_odds_back": -8.2899,
    "stem_freq": 31877,
    "language": "ru",
    "log_odds_adj": -8.1722,
    "transcription": "sovjet",
    "trial_type": "dat",
    "target": "szovjetnak",
    "prompt": "<p>Ez egy szovjet. Elneveztem a kutyámat szovjetnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szovjetnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szoftver",
    "back": 61,
    "front": 191360,
    "log_odds_back": -8.051,
    "stem_freq": 191421,
    "language": "en",
    "log_odds_adj": -8.0348,
    "transcription": "softver",
    "trial_type": "pl",
    "target": "szoftverok",
    "prompt": "<p>Ez egy szoftver. Azok ott szoftverok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szoftverok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szoftver",
    "back": 61,
    "front": 191360,
    "log_odds_back": -8.051,
    "stem_freq": 191421,
    "language": "en",
    "log_odds_adj": -8.0348,
    "transcription": "softver",
    "trial_type": "dat",
    "target": "szoftvernak",
    "prompt": "<p>Ez egy szoftver. Elneveztem a kutyámat szoftvernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szoftvernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "log_odds_adj": -7.7876,
    "transcription": "kódex",
    "trial_type": "pl",
    "target": "kódexok",
    "prompt": "<p>Ez egy kódex. Azok ott kódexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kódexok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "log_odds_adj": -7.7876,
    "transcription": "kódex",
    "trial_type": "dat",
    "target": "kódexnak",
    "prompt": "<p>Ez egy kódex. Elneveztem a kutyámat kódexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kódexnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "modell",
    "back": 231,
    "front": 523157,
    "log_odds_back": -7.7252,
    "stem_freq": 523388,
    "language": "en",
    "log_odds_adj": -7.7209,
    "transcription": "modell",
    "trial_type": "pl",
    "target": "modellok",
    "prompt": "<p>Ez egy modell. Azok ott modellok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">modellok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "modell",
    "back": 231,
    "front": 523157,
    "log_odds_back": -7.7252,
    "stem_freq": 523388,
    "language": "en",
    "log_odds_adj": -7.7209,
    "transcription": "modell",
    "trial_type": "dat",
    "target": "modellnak",
    "prompt": "<p>Ez egy modell. Elneveztem a kutyámat modellnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">modellnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "konszern",
    "back": 3,
    "front": 6888,
    "log_odds_back": -7.7389,
    "stem_freq": 6891,
    "language": "de",
    "log_odds_adj": -7.4514,
    "transcription": "konsern",
    "trial_type": "pl",
    "target": "konszernok",
    "prompt": "<p>Ez egy konszern. Azok ott konszernok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">konszernok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "konszern",
    "back": 3,
    "front": 6888,
    "log_odds_back": -7.7389,
    "stem_freq": 6891,
    "language": "de",
    "log_odds_adj": -7.4514,
    "transcription": "konsern",
    "trial_type": "dat",
    "target": "konszernnak",
    "prompt": "<p>Ez egy konszern. Elneveztem a kutyámat konszernnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">konszernnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "sláger",
    "back": 34,
    "front": 52571,
    "log_odds_back": -7.3436,
    "stem_freq": 52605,
    "language": "de",
    "log_odds_adj": -7.3146,
    "transcription": "šláger",
    "trial_type": "pl",
    "target": "slágerok",
    "prompt": "<p>Ez egy sláger. Azok ott slágerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">slágerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "sláger",
    "back": 34,
    "front": 52571,
    "log_odds_back": -7.3436,
    "stem_freq": 52605,
    "language": "de",
    "log_odds_adj": -7.3146,
    "transcription": "šláger",
    "trial_type": "dat",
    "target": "slágernak",
    "prompt": "<p>Ez egy sláger. Elneveztem a kutyámat slágernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">slágernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "mágnes",
    "back": 10,
    "front": 15983,
    "log_odds_back": -7.3767,
    "stem_freq": 15993,
    "language": "en",
    "log_odds_adj": -7.2814,
    "transcription": "mágneš",
    "trial_type": "pl",
    "target": "mágnesok",
    "prompt": "<p>Ez egy mágnes. Azok ott mágnesok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">mágnesok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "mágnes",
    "back": 10,
    "front": 15983,
    "log_odds_back": -7.3767,
    "stem_freq": 15993,
    "language": "en",
    "log_odds_adj": -7.2814,
    "transcription": "mágneš",
    "trial_type": "dat",
    "target": "mágnesnak",
    "prompt": "<p>Ez egy mágnes. Elneveztem a kutyámat mágnesnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">mágnesnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "partner",
    "back": 471,
    "front": 655199,
    "log_odds_back": -7.2378,
    "stem_freq": 655670,
    "language": "en",
    "log_odds_adj": -7.2357,
    "transcription": "partner",
    "trial_type": "pl",
    "target": "partnerok",
    "prompt": "<p>Ez egy partner. Azok ott partnerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">partnerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "partner",
    "back": 471,
    "front": 655199,
    "log_odds_back": -7.2378,
    "stem_freq": 655670,
    "language": "en",
    "log_odds_adj": -7.2357,
    "transcription": "partner",
    "trial_type": "dat",
    "target": "partnernak",
    "prompt": "<p>Ez egy partner. Elneveztem a kutyámat partnernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">partnernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "log_odds_adj": -7.1777,
    "transcription": "pollen",
    "trial_type": "pl",
    "target": "pollenok",
    "prompt": "<p>Ez egy pollen. Azok ott pollenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pollenok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "log_odds_adj": -7.1777,
    "transcription": "pollen",
    "trial_type": "dat",
    "target": "pollennak",
    "prompt": "<p>Ez egy pollen. Elneveztem a kutyámat pollennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pollennak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szlogen",
    "back": 25,
    "front": 31893,
    "log_odds_back": -7.1513,
    "stem_freq": 31918,
    "language": "en",
    "log_odds_adj": -7.1121,
    "transcription": "slogen",
    "trial_type": "pl",
    "target": "szlogenok",
    "prompt": "<p>Ez egy szlogen. Azok ott szlogenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szlogenok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szlogen",
    "back": 25,
    "front": 31893,
    "log_odds_back": -7.1513,
    "stem_freq": 31918,
    "language": "en",
    "log_odds_adj": -7.1121,
    "transcription": "slogen",
    "trial_type": "dat",
    "target": "szlogennak",
    "prompt": "<p>Ez egy szlogen. Elneveztem a kutyámat szlogennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szlogennak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bukfenc",
    "back": 3,
    "front": 3841,
    "log_odds_back": -7.1549,
    "stem_freq": 3844,
    "language": "de",
    "log_odds_adj": -6.8675,
    "transcription": "bukfenc",
    "trial_type": "pl",
    "target": "bukfencok",
    "prompt": "<p>Ez egy bukfenc. Azok ott bukfencok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bukfencok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bukfenc",
    "back": 3,
    "front": 3841,
    "log_odds_back": -7.1549,
    "stem_freq": 3844,
    "language": "de",
    "log_odds_adj": -6.8675,
    "transcription": "bukfenc",
    "trial_type": "dat",
    "target": "bukfencnak",
    "prompt": "<p>Ez egy bukfenc. Elneveztem a kutyámat bukfencnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bukfencnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "hosztesz",
    "back": 0,
    "front": 898,
    "stem_freq": 898,
    "log_odds_adj": -6.8013,
    "transcription": "hostes",
    "trial_type": "pl",
    "target": "hoszteszok",
    "prompt": "<p>Ez egy hosztesz. Azok ott hoszteszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hoszteszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "hosztesz",
    "back": 0,
    "front": 898,
    "stem_freq": 898,
    "log_odds_adj": -6.8013,
    "transcription": "hostes",
    "trial_type": "dat",
    "target": "hosztesznak",
    "prompt": "<p>Ez egy hosztesz. Elneveztem a kutyámat hosztesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hosztesznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "log_odds_adj": -6.79,
    "transcription": "ágenš",
    "trial_type": "pl",
    "target": "ágensok",
    "prompt": "<p>Ez egy ágens. Azok ott ágensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ágensok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "log_odds_adj": -6.79,
    "transcription": "ágenš",
    "trial_type": "dat",
    "target": "ágensnak",
    "prompt": "<p>Ez egy ágens. Elneveztem a kutyámat ágensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ágensnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "log_odds_adj": -6.7668,
    "transcription": "gólem",
    "trial_type": "pl",
    "target": "gólemok",
    "prompt": "<p>Ez egy gólem. Azok ott gólemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">gólemok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "log_odds_adj": -6.7668,
    "transcription": "gólem",
    "trial_type": "dat",
    "target": "gólemnak",
    "prompt": "<p>Ez egy gólem. Elneveztem a kutyámat gólemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">gólemnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "totem",
    "back": 2,
    "front": 2021,
    "log_odds_back": -6.9182,
    "stem_freq": 2023,
    "language": "en",
    "log_odds_adj": -6.5132,
    "transcription": "totem",
    "trial_type": "pl",
    "target": "totemok",
    "prompt": "<p>Ez egy totem. Azok ott totemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">totemok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "totem",
    "back": 2,
    "front": 2021,
    "log_odds_back": -6.9182,
    "stem_freq": 2023,
    "language": "en",
    "log_odds_adj": -6.5132,
    "transcription": "totem",
    "trial_type": "dat",
    "target": "totemnak",
    "prompt": "<p>Ez egy totem. Elneveztem a kutyámat totemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">totemnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "drukker",
    "back": 27,
    "front": 18506,
    "log_odds_back": -6.53,
    "stem_freq": 18533,
    "language": "de",
    "log_odds_adj": -6.4937,
    "transcription": "drukker",
    "trial_type": "pl",
    "target": "drukkerok",
    "prompt": "<p>Ez egy drukker. Azok ott drukkerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">drukkerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "drukker",
    "back": 27,
    "front": 18506,
    "log_odds_back": -6.53,
    "stem_freq": 18533,
    "language": "de",
    "log_odds_adj": -6.4937,
    "transcription": "drukker",
    "trial_type": "dat",
    "target": "drukkernak",
    "prompt": "<p>Ez egy drukker. Elneveztem a kutyámat drukkernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">drukkernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "nonszensz",
    "back": 2,
    "front": 1980,
    "log_odds_back": -6.8977,
    "stem_freq": 1982,
    "language": "en",
    "log_odds_adj": -6.4927,
    "transcription": "nonsens",
    "trial_type": "pl",
    "target": "nonszenszok",
    "prompt": "<p>Ez egy nonszensz. Azok ott nonszenszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">nonszenszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "nonszensz",
    "back": 2,
    "front": 1980,
    "log_odds_back": -6.8977,
    "stem_freq": 1982,
    "language": "en",
    "log_odds_adj": -6.4927,
    "transcription": "nonsens",
    "trial_type": "dat",
    "target": "nonszensznak",
    "prompt": "<p>Ez egy nonszensz. Elneveztem a kutyámat nonszensznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">nonszensznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "log_odds_adj": -6.375,
    "transcription": "lumen",
    "trial_type": "pl",
    "target": "lumenok",
    "prompt": "<p>Ez egy lumen. Azok ott lumenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">lumenok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "log_odds_adj": -6.375,
    "transcription": "lumen",
    "trial_type": "dat",
    "target": "lumennak",
    "prompt": "<p>Ez egy lumen. Elneveztem a kutyámat lumennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">lumennak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "token",
    "back": 6,
    "front": 3934,
    "log_odds_back": -6.4857,
    "stem_freq": 3940,
    "language": "en",
    "log_odds_adj": -6.3318,
    "transcription": "token",
    "trial_type": "pl",
    "target": "tokenok",
    "prompt": "<p>Ez egy token. Azok ott tokenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tokenok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "token",
    "back": 6,
    "front": 3934,
    "log_odds_back": -6.4857,
    "stem_freq": 3940,
    "language": "en",
    "log_odds_adj": -6.3318,
    "transcription": "token",
    "trial_type": "dat",
    "target": "tokennak",
    "prompt": "<p>Ez egy token. Elneveztem a kutyámat tokennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tokennak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "duett",
    "back": 20,
    "front": 11632,
    "log_odds_back": -6.3658,
    "stem_freq": 11652,
    "language": "it",
    "log_odds_adj": -6.3171,
    "transcription": "duett",
    "trial_type": "pl",
    "target": "duettok",
    "prompt": "<p>Ez egy duett. Azok ott duettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">duettok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "duett",
    "back": 20,
    "front": 11632,
    "log_odds_back": -6.3658,
    "stem_freq": 11652,
    "language": "it",
    "log_odds_adj": -6.3171,
    "transcription": "duett",
    "trial_type": "dat",
    "target": "duettnak",
    "prompt": "<p>Ez egy duett. Elneveztem a kutyámat duettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">duettnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kortes",
    "back": 0,
    "front": 452,
    "stem_freq": 452,
    "log_odds_adj": -6.1159,
    "transcription": "korteš",
    "trial_type": "pl",
    "target": "kortesok",
    "prompt": "<p>Ez egy kortes. Azok ott kortesok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kortesok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kortes",
    "back": 0,
    "front": 452,
    "stem_freq": 452,
    "log_odds_adj": -6.1159,
    "transcription": "korteš",
    "trial_type": "dat",
    "target": "kortesnak",
    "prompt": "<p>Ez egy kortes. Elneveztem a kutyámat kortesnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kortesnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "omlett",
    "back": 9,
    "front": 3760,
    "log_odds_back": -6.0349,
    "stem_freq": 3769,
    "language": "fr",
    "log_odds_adj": -5.9299,
    "transcription": "omlett",
    "trial_type": "pl",
    "target": "omlettok",
    "prompt": "<p>Ez egy omlett. Azok ott omlettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">omlettok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "omlett",
    "back": 9,
    "front": 3760,
    "log_odds_back": -6.0349,
    "stem_freq": 3769,
    "language": "fr",
    "log_odds_adj": -5.9299,
    "transcription": "omlett",
    "trial_type": "dat",
    "target": "omlettnak",
    "prompt": "<p>Ez egy omlett. Elneveztem a kutyámat omlettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">omlettnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "koffer",
    "back": 668,
    "front": 2175,
    "log_odds_back": -1.1805,
    "stem_freq": 2843,
    "language": "de",
    "log_odds_adj": -1.1795,
    "transcription": "koffer",
    "trial_type": "pl",
    "target": "kofferok",
    "prompt": "<p>Ez egy koffer. Azok ott kofferok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kofferok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "koffer",
    "back": 668,
    "front": 2175,
    "log_odds_back": -1.1805,
    "stem_freq": 2843,
    "language": "de",
    "log_odds_adj": -1.1795,
    "transcription": "koffer",
    "trial_type": "dat",
    "target": "koffernak",
    "prompt": "<p>Ez egy koffer. Elneveztem a kutyámat koffernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">koffernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bojler",
    "back": 312,
    "front": 915,
    "log_odds_back": -1.0759,
    "stem_freq": 1227,
    "language": "en",
    "log_odds_adj": -1.0738,
    "transcription": "bojler",
    "trial_type": "pl",
    "target": "bojlerok",
    "prompt": "<p>Ez egy bojler. Azok ott bojlerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bojlerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bojler",
    "back": 312,
    "front": 915,
    "log_odds_back": -1.0759,
    "stem_freq": 1227,
    "language": "en",
    "log_odds_adj": -1.0738,
    "transcription": "bojler",
    "trial_type": "dat",
    "target": "bojlernak",
    "prompt": "<p>Ez egy bojler. Elneveztem a kutyámat bojlernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bojlernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "farmer",
    "back": 7287,
    "front": 20249,
    "log_odds_back": -1.022,
    "stem_freq": 27536,
    "language": "en",
    "log_odds_adj": -1.0219,
    "transcription": "farmer",
    "trial_type": "pl",
    "target": "farmerok",
    "prompt": "<p>Ez egy farmer. Azok ott farmerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">farmerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "farmer",
    "back": 7287,
    "front": 20249,
    "log_odds_back": -1.022,
    "stem_freq": 27536,
    "language": "en",
    "log_odds_adj": -1.0219,
    "transcription": "farmer",
    "trial_type": "dat",
    "target": "farmernak",
    "prompt": "<p>Ez egy farmer. Elneveztem a kutyámat farmernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">farmernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "log_odds_adj": -0.9879,
    "transcription": "skander",
    "trial_type": "pl",
    "target": "szkanderok",
    "prompt": "<p>Ez egy szkander. Azok ott szkanderok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szkanderok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "log_odds_adj": -0.9879,
    "transcription": "skander",
    "trial_type": "dat",
    "target": "szkandernak",
    "prompt": "<p>Ez egy szkander. Elneveztem a kutyámat szkandernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szkandernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "log_odds_adj": -0.9324,
    "transcription": "karcer",
    "trial_type": "pl",
    "target": "karcerok",
    "prompt": "<p>Ez egy karcer. Azok ott karcerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">karcerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "log_odds_adj": -0.9324,
    "transcription": "karcer",
    "trial_type": "dat",
    "target": "karcernak",
    "prompt": "<p>Ez egy karcer. Elneveztem a kutyámat karcernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">karcernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "log_odds_adj": -0.7751,
    "transcription": "fotel",
    "trial_type": "pl",
    "target": "fotelok",
    "prompt": "<p>Ez egy fotel. Azok ott fotelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">fotelok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "log_odds_adj": -0.7751,
    "transcription": "fotel",
    "trial_type": "dat",
    "target": "fotelnak",
    "prompt": "<p>Ez egy fotel. Elneveztem a kutyámat fotelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">fotelnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "log_odds_adj": -0.7711,
    "transcription": "flanel",
    "trial_type": "pl",
    "target": "flanelok",
    "prompt": "<p>Ez egy flanel. Azok ott flanelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">flanelok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "log_odds_adj": -0.7711,
    "transcription": "flanel",
    "trial_type": "dat",
    "target": "flanelnak",
    "prompt": "<p>Ez egy flanel. Elneveztem a kutyámat flanelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">flanelnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "log_odds_adj": -0.7148,
    "transcription": "karter",
    "trial_type": "pl",
    "target": "karterok",
    "prompt": "<p>Ez egy karter. Azok ott karterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">karterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "log_odds_adj": -0.7148,
    "transcription": "karter",
    "trial_type": "dat",
    "target": "karternak",
    "prompt": "<p>Ez egy karter. Elneveztem a kutyámat karternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">karternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "log_odds_adj": -0.427,
    "transcription": "jampec",
    "trial_type": "pl",
    "target": "jampecok",
    "prompt": "<p>Ez egy jampec. Azok ott jampecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">jampecok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "log_odds_adj": -0.427,
    "transcription": "jampec",
    "trial_type": "dat",
    "target": "jampecnak",
    "prompt": "<p>Ez egy jampec. Elneveztem a kutyámat jampecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">jampecnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "log_odds_adj": -0.1341,
    "transcription": "kóter",
    "trial_type": "pl",
    "target": "kóterok",
    "prompt": "<p>Ez egy kóter. Azok ott kóterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kóterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "log_odds_adj": -0.1341,
    "transcription": "kóter",
    "trial_type": "dat",
    "target": "kóternak",
    "prompt": "<p>Ez egy kóter. Elneveztem a kutyámat kóternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kóternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "log_odds_adj": 0.282,
    "transcription": "maces",
    "trial_type": "pl",
    "target": "maceszok",
    "prompt": "<p>Ez egy macesz. Azok ott maceszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">maceszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "log_odds_adj": 0.282,
    "transcription": "maces",
    "trial_type": "dat",
    "target": "macesznak",
    "prompt": "<p>Ez egy macesz. Elneveztem a kutyámat macesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">macesznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "log_odds_adj": 0.3107,
    "transcription": "bakter",
    "trial_type": "pl",
    "target": "bakterok",
    "prompt": "<p>Ez egy bakter. Azok ott bakterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bakterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "log_odds_adj": 0.3107,
    "transcription": "bakter",
    "trial_type": "dat",
    "target": "bakternak",
    "prompt": "<p>Ez egy bakter. Elneveztem a kutyámat bakternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bakternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "log_odds_adj": 0.3642,
    "transcription": "šumer",
    "trial_type": "pl",
    "target": "sumerok",
    "prompt": "<p>Ez egy sumer. Azok ott sumerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sumerok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "log_odds_adj": 0.3642,
    "transcription": "šumer",
    "trial_type": "dat",
    "target": "sumernak",
    "prompt": "<p>Ez egy sumer. Elneveztem a kutyámat sumernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sumernak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "log_odds_adj": 0.7378,
    "transcription": "klozet",
    "trial_type": "pl",
    "target": "klozetok",
    "prompt": "<p>Ez egy klozet. Azok ott klozetok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">klozetok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "log_odds_adj": 0.7378,
    "transcription": "klozet",
    "trial_type": "dat",
    "target": "klozetnak",
    "prompt": "<p>Ez egy klozet. Elneveztem a kutyámat klozetnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">klozetnak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "log_odds_adj": 0.9424,
    "transcription": "šames",
    "trial_type": "pl",
    "target": "sameszok",
    "prompt": "<p>Ez egy samesz. Azok ott sameszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sameszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "log_odds_adj": 0.9424,
    "transcription": "šames",
    "trial_type": "dat",
    "target": "samesznak",
    "prompt": "<p>Ez egy samesz. Elneveztem a kutyámat samesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">samesznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "log_odds_adj": 1.0971,
    "transcription": "malter",
    "trial_type": "pl",
    "target": "malterok",
    "prompt": "<p>Ez egy malter. Azok ott malterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">malterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "log_odds_adj": 1.0971,
    "transcription": "malter",
    "trial_type": "dat",
    "target": "malternak",
    "prompt": "<p>Ez egy malter. Elneveztem a kutyámat malternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">malternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "log_odds_adj": 1.98,
    "transcription": "muter",
    "trial_type": "pl",
    "target": "muterok",
    "prompt": "<p>Ez egy muter. Azok ott muterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">muterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "log_odds_adj": 1.98,
    "transcription": "muter",
    "trial_type": "dat",
    "target": "muternak",
    "prompt": "<p>Ez egy muter. Elneveztem a kutyámat muternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">muternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "log_odds_adj": 2.2082,
    "transcription": "koles",
    "trial_type": "pl",
    "target": "koleszok",
    "prompt": "<p>Ez egy kolesz. Azok ott koleszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">koleszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "log_odds_adj": 2.2082,
    "transcription": "koles",
    "trial_type": "dat",
    "target": "kolesznak",
    "prompt": "<p>Ez egy kolesz. Elneveztem a kutyámat kolesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kolesznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "log_odds_adj": 2.3911,
    "transcription": "krapek",
    "trial_type": "pl",
    "target": "krapekok",
    "prompt": "<p>Ez egy krapek. Azok ott krapekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">krapekok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "log_odds_adj": 2.3911,
    "transcription": "krapek",
    "trial_type": "dat",
    "target": "krapeknak",
    "prompt": "<p>Ez egy krapek. Elneveztem a kutyámat krapeknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">krapeknak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "log_odds_adj": 2.8978,
    "transcription": "pajes",
    "trial_type": "pl",
    "target": "pajeszok",
    "prompt": "<p>Ez egy pajesz. Azok ott pajeszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pajeszok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "log_odds_adj": 2.8978,
    "transcription": "pajes",
    "trial_type": "dat",
    "target": "pajesznak",
    "prompt": "<p>Ez egy pajesz. Elneveztem a kutyámat pajesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pajesznak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "log_odds_adj": 3.139,
    "transcription": "balek",
    "trial_type": "pl",
    "target": "balekok",
    "prompt": "<p>Ez egy balek. Azok ott balekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">balekok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "log_odds_adj": 3.139,
    "transcription": "balek",
    "trial_type": "dat",
    "target": "baleknak",
    "prompt": "<p>Ez egy balek. Elneveztem a kutyámat baleknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">baleknak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "log_odds_adj": 3.2481,
    "transcription": "masek",
    "trial_type": "pl",
    "target": "maszekok",
    "prompt": "<p>Ez egy maszek. Azok ott maszekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">maszekok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "log_odds_adj": 3.2481,
    "transcription": "masek",
    "trial_type": "dat",
    "target": "maszeknak",
    "prompt": "<p>Ez egy maszek. Elneveztem a kutyámat maszeknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">maszeknak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "log_odds_adj": 3.3393,
    "transcription": "fater",
    "trial_type": "pl",
    "target": "faterok",
    "prompt": "<p>Ez egy fater. Azok ott faterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">faterok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "log_odds_adj": 3.3393,
    "transcription": "fater",
    "trial_type": "dat",
    "target": "faternak",
    "prompt": "<p>Ez egy fater. Elneveztem a kutyámat faternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">faternak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "log_odds_adj": 4.1906,
    "transcription": "matek",
    "trial_type": "pl",
    "target": "matekok",
    "prompt": "<p>Ez egy matek. Azok ott matekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">matekok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "log_odds_adj": 4.1906,
    "transcription": "matek",
    "trial_type": "dat",
    "target": "mateknak",
    "prompt": "<p>Ez egy matek. Elneveztem a kutyámat mateknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">mateknak<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "log_odds_adj": 4.7287,
    "transcription": "haver",
    "trial_type": "pl",
    "target": "haverok",
    "prompt": "<p>Ez egy haver. Azok ott haverok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">haverok<\/p>",
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "log_odds_adj": 4.7287,
    "transcription": "haver",
    "trial_type": "dat",
    "target": "havernak",
    "prompt": "<p>Ez egy haver. Elneveztem a kutyámat havernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">havernak<\/p>",
    "choices": ["f", "j"]
  }
]
