stim = [
  {
    "stem": "narem",
    "back": 9,
    "front": 18,
    "log_odds_back": -0.6419,
    "type": "non word",
    "transcription": "narem",
    "prompt": "Ez egy narem. Ezek itt...",
    "target_words": ["naremok", "naremek"]
  },
  {
    "stem": "kábesz",
    "back": 11,
    "front": 15,
    "log_odds_back": -0.2877,
    "type": "non word",
    "transcription": "kábes",
    "prompt": "Ez egy kábesz. Ezek itt...",
    "target_words": ["kábeszok", "kábeszek"]
  },
  {
    "stem": "trájeg",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "trájeg",
    "prompt": "Ez egy trájeg. Ezek itt...",
    "target_words": ["trájegok", "trájegek"]
  },
  {
    "stem": "gótem",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "gótem",
    "prompt": "Ez egy gótem. Ezek itt...",
    "target_words": ["gótemok", "gótemek"]
  },
  {
    "stem": "spatel",
    "back": 4,
    "front": 22,
    "log_odds_back": -1.5261,
    "type": "non word",
    "transcription": "špatel",
    "prompt": "Ez egy spatel. Ezek itt...",
    "target_words": ["spatelok", "spatelek"]
  },
  {
    "stem": "sporzem",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "šporzem",
    "prompt": "Ez egy sporzem. Ezek itt...",
    "target_words": ["sporzemok", "sporzemek"]
  },
  {
    "stem": "zuten",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "zuten",
    "prompt": "Ez egy zuten. Ezek itt...",
    "target_words": ["zutenok", "zutenek"]
  },
  {
    "stem": "pítend",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "pítend",
    "prompt": "Ez egy pítend. Ezek itt...",
    "target_words": ["pítendok", "pítendek"]
  },
  {
    "stem": "fincek",
    "back": 4,
    "front": 22,
    "log_odds_back": -1.5261,
    "type": "non word",
    "transcription": "fincek",
    "prompt": "Ez egy fincek. Ezek itt...",
    "target_words": ["fincekok", "fincekek"]
  },
  {
    "stem": "sartely",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "šartej",
    "prompt": "Ez egy sartely. Ezek itt...",
    "target_words": ["sartelyok", "sartelyek"]
  },
  {
    "stem": "priszec",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "prisec",
    "prompt": "Ez egy priszec. Ezek itt...",
    "target_words": ["priszecok", "priszecek"]
  },
  {
    "stem": "sprivenc",
    "back": 3,
    "front": 23,
    "log_odds_back": -1.7918,
    "type": "non word",
    "transcription": "šprivenc",
    "prompt": "Ez egy sprivenc. Ezek itt...",
    "target_words": ["sprivencok", "sprivencek"]
  },
  {
    "stem": "csimen",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "čimen",
    "prompt": "Ez egy csimen. Ezek itt...",
    "target_words": ["csimenok", "csimenek"]
  },
  {
    "stem": "braszenc",
    "back": 8,
    "front": 18,
    "log_odds_back": -0.7472,
    "type": "non word",
    "transcription": "brasenc",
    "prompt": "Ez egy braszenc. Ezek itt...",
    "target_words": ["braszencok", "braszencek"]
  },
  {
    "stem": "bidem",
    "back": 1,
    "front": 25,
    "log_odds_back": -2.5649,
    "type": "non word",
    "transcription": "bidem",
    "prompt": "Ez egy bidem. Ezek itt...",
    "target_words": ["bidemok", "bidemek"]
  },
  {
    "stem": "kliszer",
    "back": 3,
    "front": 24,
    "log_odds_back": -1.8326,
    "type": "non word",
    "transcription": "kliser",
    "prompt": "Ez egy kliszer. Ezek itt...",
    "target_words": ["kliszerok", "kliszerek"]
  },
  {
    "stem": "dingec",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "dingec",
    "prompt": "Ez egy dingec. Ezek itt...",
    "target_words": ["dingecok", "dingecek"]
  },
  {
    "stem": "fojlegy",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "fojleḏ",
    "prompt": "Ez egy fojlegy. Ezek itt...",
    "target_words": ["fojlegyok", "fojlegyek"]
  },
  {
    "stem": "surnegy",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "šurneḏ",
    "prompt": "Ez egy surnegy. Ezek itt...",
    "target_words": ["surnegyok", "surnegyek"]
  },
  {
    "stem": "vurnel",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "vurnel",
    "prompt": "Ez egy vurnel. Ezek itt...",
    "target_words": ["vurnelok", "vurnelek"]
  },
  {
    "stem": "dutec",
    "back": 6,
    "front": 21,
    "log_odds_back": -1.1451,
    "type": "non word",
    "transcription": "dutec",
    "prompt": "Ez egy dutec. Ezek itt...",
    "target_words": ["dutecok", "dutecek"]
  },
  {
    "stem": "dihely",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "dihej",
    "prompt": "Ez egy dihely. Ezek itt...",
    "target_words": ["dihelyok", "dihelyek"]
  },
  {
    "stem": "hijegy",
    "back": 3,
    "front": 24,
    "log_odds_back": -1.8326,
    "type": "non word",
    "transcription": "hijeḏ",
    "prompt": "Ez egy hijegy. Ezek itt...",
    "target_words": ["hijegyok", "hijegyek"]
  },
  {
    "stem": "dajrens",
    "back": 4,
    "front": 23,
    "log_odds_back": -1.5686,
    "type": "non word",
    "transcription": "dajrenš",
    "prompt": "Ez egy dajrens. Ezek itt...",
    "target_words": ["dajrensok", "dajrensek"]
  },
  {
    "stem": "sihen",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "šihen",
    "prompt": "Ez egy sihen. Ezek itt...",
    "target_words": ["sihenok", "sihenek"]
  },
  {
    "stem": "brigeszt",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "brigest",
    "prompt": "Ez egy brigeszt. Ezek itt...",
    "target_words": ["brigesztok", "brigesztek"]
  },
  {
    "stem": "navec",
    "back": 12,
    "front": 17,
    "log_odds_back": -0.3254,
    "type": "non word",
    "transcription": "navec",
    "prompt": "Ez egy navec. Ezek itt...",
    "target_words": ["navecok", "navecek"]
  },
  {
    "stem": "giheszt",
    "back": 2,
    "front": 27,
    "log_odds_back": -2.2336,
    "type": "non word",
    "transcription": "gihest",
    "prompt": "Ez egy giheszt. Ezek itt...",
    "target_words": ["gihesztok", "gihesztek"]
  },
  {
    "stem": "bródesz",
    "back": 6,
    "front": 20,
    "log_odds_back": -1.0986,
    "type": "non word",
    "transcription": "bródes",
    "prompt": "Ez egy bródesz. Ezek itt...",
    "target_words": ["bródeszok", "bródeszek"]
  },
  {
    "stem": "vublet",
    "back": 6,
    "front": 20,
    "log_odds_back": -1.0986,
    "type": "non word",
    "transcription": "vublet",
    "prompt": "Ez egy vublet. Ezek itt...",
    "target_words": ["vubletok", "vubletek"]
  },
  {
    "stem": "hóbens",
    "back": 5,
    "front": 22,
    "log_odds_back": -1.3437,
    "type": "non word",
    "transcription": "hóbenš",
    "prompt": "Ez egy hóbens. Ezek itt...",
    "target_words": ["hóbensok", "hóbensek"]
  },
  {
    "stem": "jurdent",
    "back": 7,
    "front": 19,
    "log_odds_back": -0.9163,
    "type": "non word",
    "transcription": "jurdent",
    "prompt": "Ez egy jurdent. Ezek itt...",
    "target_words": ["jurdentok", "jurdentek"]
  },
  {
    "stem": "rapszek",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "rapsek",
    "prompt": "Ez egy rapszek. Ezek itt...",
    "target_words": ["rapszekok", "rapszekek"]
  },
  {
    "stem": "priszkenc",
    "back": 2,
    "front": 25,
    "log_odds_back": -2.1595,
    "type": "non word",
    "transcription": "priskenc",
    "prompt": "Ez egy priszkenc. Ezek itt...",
    "target_words": ["priszkencok", "priszkencek"]
  },
  {
    "stem": "ítens",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "ítenš",
    "prompt": "Ez egy ítens. Ezek itt...",
    "target_words": ["ítensok", "ítensek"]
  },
  {
    "stem": "júder",
    "back": 10,
    "front": 19,
    "log_odds_back": -0.5978,
    "type": "non word",
    "transcription": "júder",
    "prompt": "Ez egy júder. Ezek itt...",
    "target_words": ["júderok", "júderek"]
  },
  {
    "stem": "dalenc",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "dalenc",
    "prompt": "Ez egy dalenc. Ezek itt...",
    "target_words": ["dalencok", "dalencek"]
  },
  {
    "stem": "dinelt",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "dinelt",
    "prompt": "Ez egy dinelt. Ezek itt...",
    "target_words": ["dineltok", "dineltek"]
  },
  {
    "stem": "licegy",
    "back": 2,
    "front": 24,
    "log_odds_back": -2.1203,
    "type": "non word",
    "transcription": "liceḏ",
    "prompt": "Ez egy licegy. Ezek itt...",
    "target_words": ["licegyok", "licegyek"]
  },
  {
    "stem": "klingesz",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "klinges",
    "prompt": "Ez egy klingesz. Ezek itt...",
    "target_words": ["klingeszok", "klingeszek"]
  },
  {
    "stem": "klítegy",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "klíteḏ",
    "prompt": "Ez egy klítegy. Ezek itt...",
    "target_words": ["klítegyok", "klítegyek"]
  },
  {
    "stem": "dábegy",
    "back": 4,
    "front": 23,
    "log_odds_back": -1.5686,
    "type": "non word",
    "transcription": "dábeḏ",
    "prompt": "Ez egy dábegy. Ezek itt...",
    "target_words": ["dábegyok", "dábegyek"]
  },
  {
    "stem": "prately",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "pratej",
    "prompt": "Ez egy prately. Ezek itt...",
    "target_words": ["pratelyok", "pratelyek"]
  },
  {
    "stem": "vismer",
    "back": 0,
    "front": 27,
    "log_odds_back": -3.3322,
    "type": "non word",
    "transcription": "višmer",
    "prompt": "Ez egy vismer. Ezek itt...",
    "target_words": ["vismerok", "vismerek"]
  },
  {
    "stem": "trigenc",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "trigenc",
    "prompt": "Ez egy trigenc. Ezek itt...",
    "target_words": ["trigencok", "trigencek"]
  },
  {
    "stem": "zsúdel",
    "back": 6,
    "front": 21,
    "log_odds_back": -1.1451,
    "type": "non word",
    "transcription": "žúdel",
    "prompt": "Ez egy zsúdel. Ezek itt...",
    "target_words": ["zsúdelok", "zsúdelek"]
  },
  {
    "stem": "ikszert",
    "back": 0,
    "front": 29,
    "log_odds_back": -3.4012,
    "type": "non word",
    "transcription": "iksert",
    "prompt": "Ez egy ikszert. Ezek itt...",
    "target_words": ["ikszertok", "ikszertek"]
  },
  {
    "stem": "jóbec",
    "back": 8,
    "front": 21,
    "log_odds_back": -0.8938,
    "type": "non word",
    "transcription": "jóbec",
    "prompt": "Ez egy jóbec. Ezek itt...",
    "target_words": ["jóbecok", "jóbecek"]
  },
  {
    "stem": "murdes",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "murdeš",
    "prompt": "Ez egy murdes. Ezek itt...",
    "target_words": ["murdesok", "murdesek"]
  },
  {
    "stem": "spizec",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "špizec",
    "prompt": "Ez egy spizec. Ezek itt...",
    "target_words": ["spizecok", "spizecek"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "type": "real word",
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "prompt": "Ez egy balek. Ezek itt...",
    "target_words": ["balekok", "balekek"]
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "type": "real word",
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "prompt": "Ez egy barchesz. Ezek itt...",
    "target_words": ["barcheszok", "barcheszek"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "type": "real word",
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "prompt": "Ez egy docens. Ezek itt...",
    "target_words": ["docensok", "docensek"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "type": "real word",
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "prompt": "Ez egy fater. Ezek itt...",
    "target_words": ["faterok", "faterek"]
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "type": "real word",
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "prompt": "Ez egy fráter. Ezek itt...",
    "target_words": ["fráterok", "fráterek"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "type": "real word",
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "prompt": "Ez egy gólem. Ezek itt...",
    "target_words": ["gólemok", "gólemek"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "type": "real word",
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "prompt": "Ez egy haver. Ezek itt...",
    "target_words": ["haverok", "haverek"]
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "type": "real word",
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "prompt": "Ez egy kampec. Ezek itt...",
    "target_words": ["kampecok", "kampecek"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "type": "real word",
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "prompt": "Ez egy karcer. Ezek itt...",
    "target_words": ["karcerok", "karcerek"]
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "type": "real word",
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "prompt": "Ez egy kráter. Ezek itt...",
    "target_words": ["kráterok", "kráterek"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "type": "real word",
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "prompt": "Ez egy kódex. Ezek itt...",
    "target_words": ["kódexok", "kódexek"]
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "type": "real word",
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "prompt": "Ez egy latex. Ezek itt...",
    "target_words": ["latexok", "latexek"]
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "type": "real word",
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "prompt": "Ez egy luesz. Ezek itt...",
    "target_words": ["lueszok", "lueszek"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "type": "real word",
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "prompt": "Ez egy lumen. Ezek itt...",
    "target_words": ["lumenok", "lumenek"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "type": "real word",
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "prompt": "Ez egy macesz. Ezek itt...",
    "target_words": ["maceszok", "maceszek"]
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "type": "real word",
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "prompt": "Ez egy macher. Ezek itt...",
    "target_words": ["macherok", "macherek"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "type": "real word",
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "prompt": "Ez egy maszek. Ezek itt...",
    "target_words": ["maszekok", "maszekek"]
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "type": "real word",
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "prompt": "Ez egy mater. Ezek itt...",
    "target_words": ["materok", "materek"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "type": "real word",
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "prompt": "Ez egy muter. Ezek itt...",
    "target_words": ["muterok", "muterek"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "type": "real word",
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "prompt": "Ez egy pajesz. Ezek itt...",
    "target_words": ["pajeszok", "pajeszek"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "type": "real word",
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "prompt": "Ez egy pollen. Ezek itt...",
    "target_words": ["pollenok", "pollenek"]
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "type": "real word",
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "prompt": "Ez egy pátens. Ezek itt...",
    "target_words": ["pátensok", "pátensek"]
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "type": "real word",
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "prompt": "Ez egy páter. Ezek itt...",
    "target_words": ["páterok", "páterek"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "type": "real word",
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "prompt": "Ez egy samesz. Ezek itt...",
    "target_words": ["sameszok", "sameszek"]
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "type": "real word",
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "prompt": "Ez egy sábesz. Ezek itt...",
    "target_words": ["sábeszok", "sábeszek"]
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "type": "real word",
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "prompt": "Ez egy sólet. Ezek itt...",
    "target_words": ["sóletok", "sóletek"]
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "type": "real word",
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "prompt": "Ez egy vamzer. Ezek itt...",
    "target_words": ["vamzerok", "vamzerek"]
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "type": "real word",
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "prompt": "Ez egy vátesz. Ezek itt...",
    "target_words": ["váteszok", "váteszek"]
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "type": "real word",
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "prompt": "Ez egy zacsek. Ezek itt...",
    "target_words": ["zacsekok", "zacsekek"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "type": "real word",
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "prompt": "Ez egy ágens. Ezek itt...",
    "target_words": ["ágensok", "ágensek"]
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "type": "real word",
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "prompt": "Ez egy ájer. Ezek itt...",
    "target_words": ["ájerok", "ájerek"]
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "type": "real word",
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "prompt": "Ez egy ómen. Ezek itt...",
    "target_words": ["ómenok", "ómenek"]
  },
  {
    "stem": "narem",
    "back": 9,
    "front": 18,
    "log_odds_back": -0.6419,
    "type": "non word",
    "transcription": "narem",
    "prompt": "Ez egy narem. Bízom a...",
    "target_words": ["naremban", "naremben"],
    "z": ""
  },
  {
    "stem": "kábesz",
    "back": 11,
    "front": 15,
    "log_odds_back": -0.2877,
    "type": "non word",
    "transcription": "kábes",
    "prompt": "Ez egy kábesz. Bízom a...",
    "target_words": ["kábeszban", "kábeszben"],
    "z": ""
  },
  {
    "stem": "trájeg",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "trájeg",
    "prompt": "Ez egy trájeg. Bízom a...",
    "target_words": ["trájegban", "trájegben"],
    "z": ""
  },
  {
    "stem": "gótem",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "gótem",
    "prompt": "Ez egy gótem. Bízom a...",
    "target_words": ["gótemban", "gótemben"],
    "z": ""
  },
  {
    "stem": "spatel",
    "back": 4,
    "front": 22,
    "log_odds_back": -1.5261,
    "type": "non word",
    "transcription": "špatel",
    "prompt": "Ez egy spatel. Bízom a...",
    "target_words": ["spatelban", "spatelben"],
    "z": ""
  },
  {
    "stem": "sporzem",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "šporzem",
    "prompt": "Ez egy sporzem. Bízom a...",
    "target_words": ["sporzemban", "sporzemben"],
    "z": ""
  },
  {
    "stem": "zuten",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "zuten",
    "prompt": "Ez egy zuten. Bízom a...",
    "target_words": ["zutenban", "zutenben"],
    "z": ""
  },
  {
    "stem": "pítend",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "pítend",
    "prompt": "Ez egy pítend. Bízom a...",
    "target_words": ["pítendban", "pítendben"],
    "z": ""
  },
  {
    "stem": "fincek",
    "back": 4,
    "front": 22,
    "log_odds_back": -1.5261,
    "type": "non word",
    "transcription": "fincek",
    "prompt": "Ez egy fincek. Bízom a...",
    "target_words": ["fincekban", "fincekben"],
    "z": ""
  },
  {
    "stem": "sartely",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "šartej",
    "prompt": "Ez egy sartely. Bízom a...",
    "target_words": ["sartelyban", "sartelyben"],
    "z": ""
  },
  {
    "stem": "priszec",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "prisec",
    "prompt": "Ez egy priszec. Bízom a...",
    "target_words": ["priszecban", "priszecben"],
    "z": ""
  },
  {
    "stem": "sprivenc",
    "back": 3,
    "front": 23,
    "log_odds_back": -1.7918,
    "type": "non word",
    "transcription": "šprivenc",
    "prompt": "Ez egy sprivenc. Bízom a...",
    "target_words": ["sprivencban", "sprivencben"],
    "z": ""
  },
  {
    "stem": "csimen",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "čimen",
    "prompt": "Ez egy csimen. Bízom a...",
    "target_words": ["csimenban", "csimenben"],
    "z": ""
  },
  {
    "stem": "braszenc",
    "back": 8,
    "front": 18,
    "log_odds_back": -0.7472,
    "type": "non word",
    "transcription": "brasenc",
    "prompt": "Ez egy braszenc. Bízom a...",
    "target_words": ["braszencban", "braszencben"],
    "z": ""
  },
  {
    "stem": "bidem",
    "back": 1,
    "front": 25,
    "log_odds_back": -2.5649,
    "type": "non word",
    "transcription": "bidem",
    "prompt": "Ez egy bidem. Bízom a...",
    "target_words": ["bidemban", "bidemben"],
    "z": ""
  },
  {
    "stem": "kliszer",
    "back": 3,
    "front": 24,
    "log_odds_back": -1.8326,
    "type": "non word",
    "transcription": "kliser",
    "prompt": "Ez egy kliszer. Bízom a...",
    "target_words": ["kliszerban", "kliszerben"],
    "z": ""
  },
  {
    "stem": "dingec",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "dingec",
    "prompt": "Ez egy dingec. Bízom a...",
    "target_words": ["dingecban", "dingecben"],
    "z": ""
  },
  {
    "stem": "fojlegy",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "fojleḏ",
    "prompt": "Ez egy fojlegy. Bízom a...",
    "target_words": ["fojlegyban", "fojlegyben"],
    "z": ""
  },
  {
    "stem": "surnegy",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "šurneḏ",
    "prompt": "Ez egy surnegy. Bízom a...",
    "target_words": ["surnegyban", "surnegyben"],
    "z": ""
  },
  {
    "stem": "vurnel",
    "back": 5,
    "front": 21,
    "log_odds_back": -1.2993,
    "type": "non word",
    "transcription": "vurnel",
    "prompt": "Ez egy vurnel. Bízom a...",
    "target_words": ["vurnelban", "vurnelben"],
    "z": ""
  },
  {
    "stem": "dutec",
    "back": 6,
    "front": 21,
    "log_odds_back": -1.1451,
    "type": "non word",
    "transcription": "dutec",
    "prompt": "Ez egy dutec. Bízom a...",
    "target_words": ["dutecban", "dutecben"],
    "z": ""
  },
  {
    "stem": "dihely",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "dihej",
    "prompt": "Ez egy dihely. Bízom a...",
    "target_words": ["dihelyban", "dihelyben"],
    "z": ""
  },
  {
    "stem": "hijegy",
    "back": 3,
    "front": 24,
    "log_odds_back": -1.8326,
    "type": "non word",
    "transcription": "hijeḏ",
    "prompt": "Ez egy hijegy. Bízom a...",
    "target_words": ["hijegyban", "hijegyben"],
    "z": ""
  },
  {
    "stem": "dajrens",
    "back": 4,
    "front": 23,
    "log_odds_back": -1.5686,
    "type": "non word",
    "transcription": "dajrenš",
    "prompt": "Ez egy dajrens. Bízom a...",
    "target_words": ["dajrensban", "dajrensben"],
    "z": ""
  },
  {
    "stem": "sihen",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "šihen",
    "prompt": "Ez egy sihen. Bízom a...",
    "target_words": ["sihenban", "sihenben"],
    "z": ""
  },
  {
    "stem": "brigeszt",
    "back": 1,
    "front": 26,
    "log_odds_back": -2.6027,
    "type": "non word",
    "transcription": "brigest",
    "prompt": "Ez egy brigeszt. Bízom a...",
    "target_words": ["brigesztban", "brigesztben"],
    "z": ""
  },
  {
    "stem": "navec",
    "back": 12,
    "front": 17,
    "log_odds_back": -0.3254,
    "type": "non word",
    "transcription": "navec",
    "prompt": "Ez egy navec. Bízom a...",
    "target_words": ["navecban", "navecben"],
    "z": ""
  },
  {
    "stem": "giheszt",
    "back": 2,
    "front": 27,
    "log_odds_back": -2.2336,
    "type": "non word",
    "transcription": "gihest",
    "prompt": "Ez egy giheszt. Bízom a...",
    "target_words": ["gihesztban", "gihesztben"],
    "z": ""
  },
  {
    "stem": "bródesz",
    "back": 6,
    "front": 20,
    "log_odds_back": -1.0986,
    "type": "non word",
    "transcription": "bródes",
    "prompt": "Ez egy bródesz. Bízom a...",
    "target_words": ["bródeszban", "bródeszben"],
    "z": ""
  },
  {
    "stem": "vublet",
    "back": 6,
    "front": 20,
    "log_odds_back": -1.0986,
    "type": "non word",
    "transcription": "vublet",
    "prompt": "Ez egy vublet. Bízom a...",
    "target_words": ["vubletban", "vubletben"],
    "z": ""
  },
  {
    "stem": "hóbens",
    "back": 5,
    "front": 22,
    "log_odds_back": -1.3437,
    "type": "non word",
    "transcription": "hóbenš",
    "prompt": "Ez egy hóbens. Bízom a...",
    "target_words": ["hóbensban", "hóbensben"],
    "z": ""
  },
  {
    "stem": "jurdent",
    "back": 7,
    "front": 19,
    "log_odds_back": -0.9163,
    "type": "non word",
    "transcription": "jurdent",
    "prompt": "Ez egy jurdent. Bízom a...",
    "target_words": ["jurdentban", "jurdentben"],
    "z": ""
  },
  {
    "stem": "rapszek",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "rapsek",
    "prompt": "Ez egy rapszek. Bízom a...",
    "target_words": ["rapszekban", "rapszekben"],
    "z": ""
  },
  {
    "stem": "priszkenc",
    "back": 2,
    "front": 25,
    "log_odds_back": -2.1595,
    "type": "non word",
    "transcription": "priskenc",
    "prompt": "Ez egy priszkenc. Bízom a...",
    "target_words": ["priszkencban", "priszkencben"],
    "z": ""
  },
  {
    "stem": "ítens",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "ítenš",
    "prompt": "Ez egy ítens. Bízom az...",
    "target_words": ["ítensban", "ítensben"],
    "z": "z"
  },
  {
    "stem": "júder",
    "back": 10,
    "front": 19,
    "log_odds_back": -0.5978,
    "type": "non word",
    "transcription": "júder",
    "prompt": "Ez egy júder. Bízom a...",
    "target_words": ["júderban", "júderben"],
    "z": ""
  },
  {
    "stem": "dalenc",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "dalenc",
    "prompt": "Ez egy dalenc. Bízom a...",
    "target_words": ["dalencban", "dalencben"],
    "z": ""
  },
  {
    "stem": "dinelt",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "dinelt",
    "prompt": "Ez egy dinelt. Bízom a...",
    "target_words": ["dineltban", "dineltben"],
    "z": ""
  },
  {
    "stem": "licegy",
    "back": 2,
    "front": 24,
    "log_odds_back": -2.1203,
    "type": "non word",
    "transcription": "liceḏ",
    "prompt": "Ez egy licegy. Bízom a...",
    "target_words": ["licegyban", "licegyben"],
    "z": ""
  },
  {
    "stem": "klingesz",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "klinges",
    "prompt": "Ez egy klingesz. Bízom a...",
    "target_words": ["klingeszban", "klingeszben"],
    "z": ""
  },
  {
    "stem": "klítegy",
    "back": 4,
    "front": 25,
    "log_odds_back": -1.6487,
    "type": "non word",
    "transcription": "klíteḏ",
    "prompt": "Ez egy klítegy. Bízom a...",
    "target_words": ["klítegyban", "klítegyben"],
    "z": ""
  },
  {
    "stem": "dábegy",
    "back": 4,
    "front": 23,
    "log_odds_back": -1.5686,
    "type": "non word",
    "transcription": "dábeḏ",
    "prompt": "Ez egy dábegy. Bízom a...",
    "target_words": ["dábegyban", "dábegyben"],
    "z": ""
  },
  {
    "stem": "prately",
    "back": 6,
    "front": 23,
    "log_odds_back": -1.2321,
    "type": "non word",
    "transcription": "pratej",
    "prompt": "Ez egy prately. Bízom a...",
    "target_words": ["pratelyban", "pratelyben"],
    "z": ""
  },
  {
    "stem": "vismer",
    "back": 0,
    "front": 27,
    "log_odds_back": -3.3322,
    "type": "non word",
    "transcription": "višmer",
    "prompt": "Ez egy vismer. Bízom a...",
    "target_words": ["vismerban", "vismerben"],
    "z": ""
  },
  {
    "stem": "trigenc",
    "back": 1,
    "front": 28,
    "log_odds_back": -2.6741,
    "type": "non word",
    "transcription": "trigenc",
    "prompt": "Ez egy trigenc. Bízom a...",
    "target_words": ["trigencban", "trigencben"],
    "z": ""
  },
  {
    "stem": "zsúdel",
    "back": 6,
    "front": 21,
    "log_odds_back": -1.1451,
    "type": "non word",
    "transcription": "žúdel",
    "prompt": "Ez egy zsúdel. Bízom a...",
    "target_words": ["zsúdelban", "zsúdelben"],
    "z": ""
  },
  {
    "stem": "ikszert",
    "back": 0,
    "front": 29,
    "log_odds_back": -3.4012,
    "type": "non word",
    "transcription": "iksert",
    "prompt": "Ez egy ikszert. Bízom az...",
    "target_words": ["ikszertban", "ikszertben"],
    "z": "z"
  },
  {
    "stem": "jóbec",
    "back": 8,
    "front": 21,
    "log_odds_back": -0.8938,
    "type": "non word",
    "transcription": "jóbec",
    "prompt": "Ez egy jóbec. Bízom a...",
    "target_words": ["jóbecban", "jóbecben"],
    "z": ""
  },
  {
    "stem": "murdes",
    "back": 9,
    "front": 17,
    "log_odds_back": -0.5878,
    "type": "non word",
    "transcription": "murdeš",
    "prompt": "Ez egy murdes. Bízom a...",
    "target_words": ["murdesban", "murdesben"],
    "z": ""
  },
  {
    "stem": "spizec",
    "back": 3,
    "front": 26,
    "log_odds_back": -1.9095,
    "type": "non word",
    "transcription": "špizec",
    "prompt": "Ez egy spizec. Bízom a...",
    "target_words": ["spizecban", "spizecben"],
    "z": ""
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "type": "real word",
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "prompt": "Ez egy balek. Bízom a...",
    "target_words": ["balekban", "balekben"],
    "z": ""
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "type": "real word",
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "prompt": "Ez egy barchesz. Bízom a...",
    "target_words": ["barcheszban", "barcheszben"],
    "z": ""
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "type": "real word",
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "prompt": "Ez egy docens. Bízom a...",
    "target_words": ["docensban", "docensben"],
    "z": ""
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "type": "real word",
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "prompt": "Ez egy fater. Bízom a...",
    "target_words": ["faterban", "faterben"],
    "z": ""
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "type": "real word",
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "prompt": "Ez egy fráter. Bízom a...",
    "target_words": ["fráterban", "fráterben"],
    "z": ""
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "type": "real word",
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "prompt": "Ez egy gólem. Bízom a...",
    "target_words": ["gólemban", "gólemben"],
    "z": ""
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "type": "real word",
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "prompt": "Ez egy haver. Bízom a...",
    "target_words": ["haverban", "haverben"],
    "z": ""
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "type": "real word",
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "prompt": "Ez egy kampec. Bízom a...",
    "target_words": ["kampecban", "kampecben"],
    "z": ""
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "type": "real word",
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "prompt": "Ez egy karcer. Bízom a...",
    "target_words": ["karcerban", "karcerben"],
    "z": ""
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "type": "real word",
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "prompt": "Ez egy kráter. Bízom a...",
    "target_words": ["kráterban", "kráterben"],
    "z": ""
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "type": "real word",
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "prompt": "Ez egy kódex. Bízom a...",
    "target_words": ["kódexban", "kódexben"],
    "z": ""
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "type": "real word",
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "prompt": "Ez egy latex. Bízom a...",
    "target_words": ["latexban", "latexben"],
    "z": ""
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "type": "real word",
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "prompt": "Ez egy luesz. Bízom a...",
    "target_words": ["lueszban", "lueszben"],
    "z": ""
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "type": "real word",
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "prompt": "Ez egy lumen. Bízom a...",
    "target_words": ["lumenban", "lumenben"],
    "z": ""
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "type": "real word",
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "prompt": "Ez egy macesz. Bízom a...",
    "target_words": ["maceszban", "maceszben"],
    "z": ""
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "type": "real word",
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "prompt": "Ez egy macher. Bízom a...",
    "target_words": ["macherban", "macherben"],
    "z": ""
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "type": "real word",
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "prompt": "Ez egy maszek. Bízom a...",
    "target_words": ["maszekban", "maszekben"],
    "z": ""
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "type": "real word",
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "prompt": "Ez egy mater. Bízom a...",
    "target_words": ["materban", "materben"],
    "z": ""
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "type": "real word",
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "prompt": "Ez egy muter. Bízom a...",
    "target_words": ["muterban", "muterben"],
    "z": ""
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "type": "real word",
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "prompt": "Ez egy pajesz. Bízom a...",
    "target_words": ["pajeszban", "pajeszben"],
    "z": ""
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "type": "real word",
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "prompt": "Ez egy pollen. Bízom a...",
    "target_words": ["pollenban", "pollenben"],
    "z": ""
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "type": "real word",
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "prompt": "Ez egy pátens. Bízom a...",
    "target_words": ["pátensban", "pátensben"],
    "z": ""
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "type": "real word",
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "prompt": "Ez egy páter. Bízom a...",
    "target_words": ["páterban", "páterben"],
    "z": ""
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "type": "real word",
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "prompt": "Ez egy samesz. Bízom a...",
    "target_words": ["sameszban", "sameszben"],
    "z": ""
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "type": "real word",
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "prompt": "Ez egy sábesz. Bízom a...",
    "target_words": ["sábeszban", "sábeszben"],
    "z": ""
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "type": "real word",
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "prompt": "Ez egy sólet. Bízom a...",
    "target_words": ["sóletban", "sóletben"],
    "z": ""
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "type": "real word",
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "prompt": "Ez egy vamzer. Bízom a...",
    "target_words": ["vamzerban", "vamzerben"],
    "z": ""
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "type": "real word",
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "prompt": "Ez egy vátesz. Bízom a...",
    "target_words": ["váteszban", "váteszben"],
    "z": ""
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "type": "real word",
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "prompt": "Ez egy zacsek. Bízom a...",
    "target_words": ["zacsekban", "zacsekben"],
    "z": ""
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "type": "real word",
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "prompt": "Ez egy ágens. Bízom az...",
    "target_words": ["ágensban", "ágensben"],
    "z": "z"
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "type": "real word",
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "prompt": "Ez egy ájer. Bízom az...",
    "target_words": ["ájerban", "ájerben"],
    "z": "z"
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "type": "real word",
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "prompt": "Ez egy ómen. Bízom az...",
    "target_words": ["ómenban", "ómenben"],
    "z": "z"
  }
]
