stim = [
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "z": "",
    "trial_type": "pl_back",
    "target": "balekok",
    "prompt": "Ez egy balek. Ezek itt balekok.",
    "stimulus": "<p style=\"font-size:48px;\">balekok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "z": "",
    "trial_type": "pl_front",
    "target": "balekek",
    "prompt": "Ez egy balek. Ezek itt balekek.",
    "stimulus": "<p style=\"font-size:48px;\">balekek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "z": "",
    "trial_type": "ine_back",
    "target": "balekban",
    "prompt": "Ez egy balek. Bízom a balekban.",
    "stimulus": "<p style=\"font-size:48px;\">balekban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "balek",
    "back": 5215,
    "front": 225,
    "log_odds_back": 3.1432,
    "stem_freq": 5440,
    "language": "yi",
    "transcription": "balek",
    "z": "",
    "trial_type": "ine_front",
    "target": "balekben",
    "prompt": "Ez egy balek. Bízom a balekben.",
    "stimulus": "<p style=\"font-size:48px;\">balekben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "z": "",
    "trial_type": "pl_back",
    "target": "barcheszok",
    "prompt": "Ez egy barchesz. Ezek itt barcheszok.",
    "stimulus": "<p style=\"font-size:48px;\">barcheszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "z": "",
    "trial_type": "pl_front",
    "target": "barcheszek",
    "prompt": "Ez egy barchesz. Ezek itt barcheszek.",
    "stimulus": "<p style=\"font-size:48px;\">barcheszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "z": "",
    "trial_type": "ine_back",
    "target": "barcheszban",
    "prompt": "Ez egy barchesz. Bízom a barcheszban.",
    "stimulus": "<p style=\"font-size:48px;\">barcheszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "barchesz",
    "back": 8,
    "front": 37,
    "log_odds_back": -1.5315,
    "stem_freq": 45,
    "language": "yi",
    "transcription": "barches",
    "z": "",
    "trial_type": "ine_front",
    "target": "barcheszben",
    "prompt": "Ez egy barchesz. Bízom a barcheszben.",
    "stimulus": "<p style=\"font-size:48px;\">barcheszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "z": "",
    "trial_type": "pl_back",
    "target": "docensok",
    "prompt": "Ez egy docens. Ezek itt docensok.",
    "stimulus": "<p style=\"font-size:48px;\">docensok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "z": "",
    "trial_type": "pl_front",
    "target": "docensek",
    "prompt": "Ez egy docens. Ezek itt docensek.",
    "stimulus": "<p style=\"font-size:48px;\">docensek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "z": "",
    "trial_type": "ine_back",
    "target": "docensban",
    "prompt": "Ez egy docens. Bízom a docensban.",
    "stimulus": "<p style=\"font-size:48px;\">docensban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "docens",
    "back": 6,
    "front": 29878,
    "log_odds_back": -8.5131,
    "stem_freq": 29884,
    "language": "la",
    "transcription": "docenš",
    "z": "",
    "trial_type": "ine_front",
    "target": "docensben",
    "prompt": "Ez egy docens. Bízom a docensben.",
    "stimulus": "<p style=\"font-size:48px;\">docensben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "z": "",
    "trial_type": "pl_back",
    "target": "faterok",
    "prompt": "Ez egy fater. Ezek itt faterok.",
    "stimulus": "<p style=\"font-size:48px;\">faterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "z": "",
    "trial_type": "pl_front",
    "target": "faterek",
    "prompt": "Ez egy fater. Ezek itt faterek.",
    "stimulus": "<p style=\"font-size:48px;\">faterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "z": "",
    "trial_type": "ine_back",
    "target": "faterban",
    "prompt": "Ez egy fater. Bízom a faterban.",
    "stimulus": "<p style=\"font-size:48px;\">faterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fater",
    "back": 5385,
    "front": 190,
    "log_odds_back": 3.3443,
    "stem_freq": 5575,
    "language": "yi",
    "transcription": "fater",
    "z": "",
    "trial_type": "ine_front",
    "target": "faterben",
    "prompt": "Ez egy fater. Bízom a faterben.",
    "stimulus": "<p style=\"font-size:48px;\">faterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "z": "",
    "trial_type": "pl_back",
    "target": "fráterok",
    "prompt": "Ez egy fráter. Ezek itt fráterok.",
    "stimulus": "<p style=\"font-size:48px;\">fráterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "z": "",
    "trial_type": "pl_front",
    "target": "fráterek",
    "prompt": "Ez egy fráter. Ezek itt fráterek.",
    "stimulus": "<p style=\"font-size:48px;\">fráterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "z": "",
    "trial_type": "ine_back",
    "target": "fráterban",
    "prompt": "Ez egy fráter. Bízom a fráterban.",
    "stimulus": "<p style=\"font-size:48px;\">fráterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fráter",
    "back": 34,
    "front": 997,
    "log_odds_back": -3.3784,
    "stem_freq": 1031,
    "language": "la",
    "transcription": "fráter",
    "z": "",
    "trial_type": "ine_front",
    "target": "fráterben",
    "prompt": "Ez egy fráter. Bízom a fráterben.",
    "stimulus": "<p style=\"font-size:48px;\">fráterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "z": "",
    "trial_type": "pl_back",
    "target": "gólemok",
    "prompt": "Ez egy gólem. Ezek itt gólemok.",
    "stimulus": "<p style=\"font-size:48px;\">gólemok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "z": "",
    "trial_type": "pl_front",
    "target": "gólemek",
    "prompt": "Ez egy gólem. Ezek itt gólemek.",
    "stimulus": "<p style=\"font-size:48px;\">gólemek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "z": "",
    "trial_type": "ine_back",
    "target": "gólemban",
    "prompt": "Ez egy gólem. Bízom a gólemban.",
    "stimulus": "<p style=\"font-size:48px;\">gólemban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "gólem",
    "back": 1,
    "front": 1736,
    "log_odds_back": -7.4593,
    "stem_freq": 1737,
    "language": "yi",
    "transcription": "gólem",
    "z": "",
    "trial_type": "ine_front",
    "target": "gólemben",
    "prompt": "Ez egy gólem. Bízom a gólemben.",
    "stimulus": "<p style=\"font-size:48px;\">gólemben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "z": "",
    "trial_type": "pl_back",
    "target": "haverok",
    "prompt": "Ez egy haver. Ezek itt haverok.",
    "stimulus": "<p style=\"font-size:48px;\">haverok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "z": "",
    "trial_type": "pl_front",
    "target": "haverek",
    "prompt": "Ez egy haver. Ezek itt haverek.",
    "stimulus": "<p style=\"font-size:48px;\">haverek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "z": "",
    "trial_type": "ine_back",
    "target": "haverban",
    "prompt": "Ez egy haver. Bízom a haverban.",
    "stimulus": "<p style=\"font-size:48px;\">haverban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "haver",
    "back": 71848,
    "front": 634,
    "log_odds_back": 4.7303,
    "stem_freq": 72482,
    "language": "yi",
    "transcription": "haver",
    "z": "",
    "trial_type": "ine_front",
    "target": "haverben",
    "prompt": "Ez egy haver. Bízom a haverben.",
    "stimulus": "<p style=\"font-size:48px;\">haverben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "z": "",
    "trial_type": "pl_back",
    "target": "kampecok",
    "prompt": "Ez egy kampec. Ezek itt kampecok.",
    "stimulus": "<p style=\"font-size:48px;\">kampecok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "z": "",
    "trial_type": "pl_front",
    "target": "kampecek",
    "prompt": "Ez egy kampec. Ezek itt kampecek.",
    "stimulus": "<p style=\"font-size:48px;\">kampecek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "z": "",
    "trial_type": "ine_back",
    "target": "kampecban",
    "prompt": "Ez egy kampec. Bízom a kampecban.",
    "stimulus": "<p style=\"font-size:48px;\">kampecban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kampec",
    "back": 41,
    "front": 30,
    "log_odds_back": 0.3124,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "kampec",
    "z": "",
    "trial_type": "ine_front",
    "target": "kampecben",
    "prompt": "Ez egy kampec. Bízom a kampecben.",
    "stimulus": "<p style=\"font-size:48px;\">kampecben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "z": "",
    "trial_type": "pl_back",
    "target": "karcerok",
    "prompt": "Ez egy karcer. Ezek itt karcerok.",
    "stimulus": "<p style=\"font-size:48px;\">karcerok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "z": "",
    "trial_type": "pl_front",
    "target": "karcerek",
    "prompt": "Ez egy karcer. Ezek itt karcerek.",
    "stimulus": "<p style=\"font-size:48px;\">karcerek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "z": "",
    "trial_type": "ine_back",
    "target": "karcerban",
    "prompt": "Ez egy karcer. Bízom a karcerban.",
    "stimulus": "<p style=\"font-size:48px;\">karcerban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "karcer",
    "back": 36,
    "front": 93,
    "log_odds_back": -0.9491,
    "stem_freq": 129,
    "language": "la",
    "transcription": "karcer",
    "z": "",
    "trial_type": "ine_front",
    "target": "karcerben",
    "prompt": "Ez egy karcer. Bízom a karcerben.",
    "stimulus": "<p style=\"font-size:48px;\">karcerben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "z": "",
    "trial_type": "pl_back",
    "target": "kráterok",
    "prompt": "Ez egy kráter. Ezek itt kráterok.",
    "stimulus": "<p style=\"font-size:48px;\">kráterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "z": "",
    "trial_type": "pl_front",
    "target": "kráterek",
    "prompt": "Ez egy kráter. Ezek itt kráterek.",
    "stimulus": "<p style=\"font-size:48px;\">kráterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "z": "",
    "trial_type": "ine_back",
    "target": "kráterban",
    "prompt": "Ez egy kráter. Bízom a kráterban.",
    "stimulus": "<p style=\"font-size:48px;\">kráterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kráter",
    "back": 87,
    "front": 9093,
    "log_odds_back": -4.6494,
    "stem_freq": 9180,
    "language": "la",
    "transcription": "kráter",
    "z": "",
    "trial_type": "ine_front",
    "target": "kráterben",
    "prompt": "Ez egy kráter. Bízom a kráterben.",
    "stimulus": "<p style=\"font-size:48px;\">kráterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "z": "",
    "trial_type": "pl_back",
    "target": "kódexok",
    "prompt": "Ez egy kódex. Ezek itt kódexok.",
    "stimulus": "<p style=\"font-size:48px;\">kódexok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "z": "",
    "trial_type": "pl_front",
    "target": "kódexek",
    "prompt": "Ez egy kódex. Ezek itt kódexek.",
    "stimulus": "<p style=\"font-size:48px;\">kódexek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "z": "",
    "trial_type": "ine_back",
    "target": "kódexban",
    "prompt": "Ez egy kódex. Bízom a kódexban.",
    "stimulus": "<p style=\"font-size:48px;\">kódexban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kódex",
    "back": 19,
    "front": 48210,
    "log_odds_back": -7.8389,
    "stem_freq": 48229,
    "language": "la",
    "transcription": "kódex",
    "z": "",
    "trial_type": "ine_front",
    "target": "kódexben",
    "prompt": "Ez egy kódex. Bízom a kódexben.",
    "stimulus": "<p style=\"font-size:48px;\">kódexben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "z": "",
    "trial_type": "pl_back",
    "target": "latexok",
    "prompt": "Ez egy latex. Ezek itt latexok.",
    "stimulus": "<p style=\"font-size:48px;\">latexok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "z": "",
    "trial_type": "pl_front",
    "target": "latexek",
    "prompt": "Ez egy latex. Ezek itt latexek.",
    "stimulus": "<p style=\"font-size:48px;\">latexek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "z": "",
    "trial_type": "ine_back",
    "target": "latexban",
    "prompt": "Ez egy latex. Bízom a latexban.",
    "stimulus": "<p style=\"font-size:48px;\">latexban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "latex",
    "back": 125,
    "front": 2639,
    "log_odds_back": -3.0498,
    "stem_freq": 2764,
    "language": "la",
    "transcription": "latex",
    "z": "",
    "trial_type": "ine_front",
    "target": "latexben",
    "prompt": "Ez egy latex. Bízom a latexben.",
    "stimulus": "<p style=\"font-size:48px;\">latexben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "z": "",
    "trial_type": "pl_back",
    "target": "lueszok",
    "prompt": "Ez egy luesz. Ezek itt lueszok.",
    "stimulus": "<p style=\"font-size:48px;\">lueszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "z": "",
    "trial_type": "pl_front",
    "target": "lueszek",
    "prompt": "Ez egy luesz. Ezek itt lueszek.",
    "stimulus": "<p style=\"font-size:48px;\">lueszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "z": "",
    "trial_type": "ine_back",
    "target": "lueszban",
    "prompt": "Ez egy luesz. Bízom a lueszban.",
    "stimulus": "<p style=\"font-size:48px;\">lueszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "luesz",
    "back": 1,
    "front": 22,
    "log_odds_back": -3.091,
    "stem_freq": 23,
    "language": "la",
    "transcription": "lues",
    "z": "",
    "trial_type": "ine_front",
    "target": "lueszben",
    "prompt": "Ez egy luesz. Bízom a lueszben.",
    "stimulus": "<p style=\"font-size:48px;\">lueszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "z": "",
    "trial_type": "pl_back",
    "target": "lumenok",
    "prompt": "Ez egy lumen. Ezek itt lumenok.",
    "stimulus": "<p style=\"font-size:48px;\">lumenok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "z": "",
    "trial_type": "pl_front",
    "target": "lumenek",
    "prompt": "Ez egy lumen. Ezek itt lumenek.",
    "stimulus": "<p style=\"font-size:48px;\">lumenek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "z": "",
    "trial_type": "ine_back",
    "target": "lumenban",
    "prompt": "Ez egy lumen. Bízom a lumenban.",
    "stimulus": "<p style=\"font-size:48px;\">lumenban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "lumen",
    "back": 2,
    "front": 1760,
    "log_odds_back": -6.7799,
    "stem_freq": 1762,
    "language": "la",
    "transcription": "lumen",
    "z": "",
    "trial_type": "ine_front",
    "target": "lumenben",
    "prompt": "Ez egy lumen. Bízom a lumenben.",
    "stimulus": "<p style=\"font-size:48px;\">lumenben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "z": "",
    "trial_type": "pl_back",
    "target": "maceszok",
    "prompt": "Ez egy macesz. Ezek itt maceszok.",
    "stimulus": "<p style=\"font-size:48px;\">maceszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "z": "",
    "trial_type": "pl_front",
    "target": "maceszek",
    "prompt": "Ez egy macesz. Ezek itt maceszek.",
    "stimulus": "<p style=\"font-size:48px;\">maceszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "z": "",
    "trial_type": "ine_back",
    "target": "maceszban",
    "prompt": "Ez egy macesz. Bízom a maceszban.",
    "stimulus": "<p style=\"font-size:48px;\">maceszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "macesz",
    "back": 117,
    "front": 88,
    "log_odds_back": 0.2848,
    "stem_freq": 205,
    "language": "yi",
    "transcription": "maces",
    "z": "",
    "trial_type": "ine_front",
    "target": "maceszben",
    "prompt": "Ez egy macesz. Bízom a maceszben.",
    "stimulus": "<p style=\"font-size:48px;\">maceszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "z": "",
    "trial_type": "pl_back",
    "target": "macherok",
    "prompt": "Ez egy macher. Ezek itt macherok.",
    "stimulus": "<p style=\"font-size:48px;\">macherok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "z": "",
    "trial_type": "pl_front",
    "target": "macherek",
    "prompt": "Ez egy macher. Ezek itt macherek.",
    "stimulus": "<p style=\"font-size:48px;\">macherek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "z": "",
    "trial_type": "ine_back",
    "target": "macherban",
    "prompt": "Ez egy macher. Bízom a macherban.",
    "stimulus": "<p style=\"font-size:48px;\">macherban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "macher",
    "back": 14,
    "front": 40,
    "log_odds_back": -1.0498,
    "stem_freq": 54,
    "language": "yi",
    "transcription": "macher",
    "z": "",
    "trial_type": "ine_front",
    "target": "macherben",
    "prompt": "Ez egy macher. Bízom a macherben.",
    "stimulus": "<p style=\"font-size:48px;\">macherben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "z": "",
    "trial_type": "pl_back",
    "target": "maszekok",
    "prompt": "Ez egy maszek. Ezek itt maszekok.",
    "stimulus": "<p style=\"font-size:48px;\">maszekok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "z": "",
    "trial_type": "pl_front",
    "target": "maszekek",
    "prompt": "Ez egy maszek. Ezek itt maszekek.",
    "stimulus": "<p style=\"font-size:48px;\">maszekek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "z": "",
    "trial_type": "ine_back",
    "target": "maszekban",
    "prompt": "Ez egy maszek. Bízom a maszekban.",
    "stimulus": "<p style=\"font-size:48px;\">maszekban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "maszek",
    "back": 2084,
    "front": 80,
    "log_odds_back": 3.26,
    "stem_freq": 2164,
    "language": "yi",
    "transcription": "masek",
    "z": "",
    "trial_type": "ine_front",
    "target": "maszekben",
    "prompt": "Ez egy maszek. Bízom a maszekben.",
    "stimulus": "<p style=\"font-size:48px;\">maszekben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "z": "",
    "trial_type": "pl_back",
    "target": "materok",
    "prompt": "Ez egy mater. Ezek itt materok.",
    "stimulus": "<p style=\"font-size:48px;\">materok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "z": "",
    "trial_type": "pl_front",
    "target": "materek",
    "prompt": "Ez egy mater. Ezek itt materek.",
    "stimulus": "<p style=\"font-size:48px;\">materek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "z": "",
    "trial_type": "ine_back",
    "target": "materban",
    "prompt": "Ez egy mater. Bízom a materban.",
    "stimulus": "<p style=\"font-size:48px;\">materban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "mater",
    "back": 193,
    "front": 2954,
    "log_odds_back": -2.7282,
    "stem_freq": 3147,
    "language": "la",
    "transcription": "mater",
    "z": "",
    "trial_type": "ine_front",
    "target": "materben",
    "prompt": "Ez egy mater. Bízom a materben.",
    "stimulus": "<p style=\"font-size:48px;\">materben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "z": "",
    "trial_type": "pl_back",
    "target": "muterok",
    "prompt": "Ez egy muter. Ezek itt muterok.",
    "stimulus": "<p style=\"font-size:48px;\">muterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "z": "",
    "trial_type": "pl_front",
    "target": "muterek",
    "prompt": "Ez egy muter. Ezek itt muterek.",
    "stimulus": "<p style=\"font-size:48px;\">muterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "z": "",
    "trial_type": "ine_back",
    "target": "muterban",
    "prompt": "Ez egy muter. Bízom a muterban.",
    "stimulus": "<p style=\"font-size:48px;\">muterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "muter",
    "back": 745,
    "front": 102,
    "log_odds_back": 1.9884,
    "stem_freq": 847,
    "language": "yi",
    "transcription": "muter",
    "z": "",
    "trial_type": "ine_front",
    "target": "muterben",
    "prompt": "Ez egy muter. Bízom a muterben.",
    "stimulus": "<p style=\"font-size:48px;\">muterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "z": "",
    "trial_type": "pl_back",
    "target": "pajeszok",
    "prompt": "Ez egy pajesz. Ezek itt pajeszok.",
    "stimulus": "<p style=\"font-size:48px;\">pajeszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "z": "",
    "trial_type": "pl_front",
    "target": "pajeszek",
    "prompt": "Ez egy pajesz. Ezek itt pajeszek.",
    "stimulus": "<p style=\"font-size:48px;\">pajeszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "z": "",
    "trial_type": "ine_back",
    "target": "pajeszban",
    "prompt": "Ez egy pajesz. Bízom a pajeszban.",
    "stimulus": "<p style=\"font-size:48px;\">pajeszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pajesz",
    "back": 271,
    "front": 14,
    "log_odds_back": 2.9631,
    "stem_freq": 285,
    "language": "yi",
    "transcription": "pajes",
    "z": "",
    "trial_type": "ine_front",
    "target": "pajeszben",
    "prompt": "Ez egy pajesz. Bízom a pajeszben.",
    "stimulus": "<p style=\"font-size:48px;\">pajeszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "z": "",
    "trial_type": "pl_back",
    "target": "pollenok",
    "prompt": "Ez egy pollen. Ezek itt pollenok.",
    "stimulus": "<p style=\"font-size:48px;\">pollenok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "z": "",
    "trial_type": "pl_front",
    "target": "pollenek",
    "prompt": "Ez egy pollen. Ezek itt pollenek.",
    "stimulus": "<p style=\"font-size:48px;\">pollenek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "z": "",
    "trial_type": "ine_back",
    "target": "pollenban",
    "prompt": "Ez egy pollen. Bízom a pollenban.",
    "stimulus": "<p style=\"font-size:48px;\">pollenban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pollen",
    "back": 7,
    "front": 10478,
    "log_odds_back": -7.3111,
    "stem_freq": 10485,
    "language": "la",
    "transcription": "pollen",
    "z": "",
    "trial_type": "ine_front",
    "target": "pollenben",
    "prompt": "Ez egy pollen. Bízom a pollenben.",
    "stimulus": "<p style=\"font-size:48px;\">pollenben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "z": "",
    "trial_type": "pl_back",
    "target": "pátensok",
    "prompt": "Ez egy pátens. Ezek itt pátensok.",
    "stimulus": "<p style=\"font-size:48px;\">pátensok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "z": "",
    "trial_type": "pl_front",
    "target": "pátensek",
    "prompt": "Ez egy pátens. Ezek itt pátensek.",
    "stimulus": "<p style=\"font-size:48px;\">pátensek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "z": "",
    "trial_type": "ine_back",
    "target": "pátensban",
    "prompt": "Ez egy pátens. Bízom a pátensban.",
    "stimulus": "<p style=\"font-size:48px;\">pátensban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "pátens",
    "back": 2,
    "front": 616,
    "log_odds_back": -5.7301,
    "stem_freq": 618,
    "language": "la",
    "transcription": "pátenš",
    "z": "",
    "trial_type": "ine_front",
    "target": "pátensben",
    "prompt": "Ez egy pátens. Bízom a pátensben.",
    "stimulus": "<p style=\"font-size:48px;\">pátensben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "z": "",
    "trial_type": "pl_back",
    "target": "páterok",
    "prompt": "Ez egy páter. Ezek itt páterok.",
    "stimulus": "<p style=\"font-size:48px;\">páterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "z": "",
    "trial_type": "pl_front",
    "target": "páterek",
    "prompt": "Ez egy páter. Ezek itt páterek.",
    "stimulus": "<p style=\"font-size:48px;\">páterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "z": "",
    "trial_type": "ine_back",
    "target": "páterban",
    "prompt": "Ez egy páter. Bízom a páterban.",
    "stimulus": "<p style=\"font-size:48px;\">páterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "páter",
    "back": 32,
    "front": 923,
    "log_odds_back": -3.3619,
    "stem_freq": 955,
    "language": "la",
    "transcription": "páter",
    "z": "",
    "trial_type": "ine_front",
    "target": "páterben",
    "prompt": "Ez egy páter. Bízom a páterben.",
    "stimulus": "<p style=\"font-size:48px;\">páterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "z": "",
    "trial_type": "pl_back",
    "target": "sameszok",
    "prompt": "Ez egy samesz. Ezek itt sameszok.",
    "stimulus": "<p style=\"font-size:48px;\">sameszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "z": "",
    "trial_type": "pl_front",
    "target": "sameszek",
    "prompt": "Ez egy samesz. Ezek itt sameszek.",
    "stimulus": "<p style=\"font-size:48px;\">sameszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "z": "",
    "trial_type": "ine_back",
    "target": "sameszban",
    "prompt": "Ez egy samesz. Bízom a sameszban.",
    "stimulus": "<p style=\"font-size:48px;\">sameszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "samesz",
    "back": 484,
    "front": 188,
    "log_odds_back": 0.9456,
    "stem_freq": 672,
    "language": "yi",
    "transcription": "šames",
    "z": "",
    "trial_type": "ine_front",
    "target": "sameszben",
    "prompt": "Ez egy samesz. Bízom a sameszben.",
    "stimulus": "<p style=\"font-size:48px;\">sameszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "z": "",
    "trial_type": "pl_back",
    "target": "sábeszok",
    "prompt": "Ez egy sábesz. Ezek itt sábeszok.",
    "stimulus": "<p style=\"font-size:48px;\">sábeszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "z": "",
    "trial_type": "pl_front",
    "target": "sábeszek",
    "prompt": "Ez egy sábesz. Ezek itt sábeszek.",
    "stimulus": "<p style=\"font-size:48px;\">sábeszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "z": "",
    "trial_type": "ine_back",
    "target": "sábeszban",
    "prompt": "Ez egy sábesz. Bízom a sábeszban.",
    "stimulus": "<p style=\"font-size:48px;\">sábeszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sábesz",
    "back": 10,
    "front": 102,
    "log_odds_back": -2.3224,
    "stem_freq": 112,
    "language": "yi",
    "transcription": "šábes",
    "z": "",
    "trial_type": "ine_front",
    "target": "sábeszben",
    "prompt": "Ez egy sábesz. Bízom a sábeszben.",
    "stimulus": "<p style=\"font-size:48px;\">sábeszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "z": "",
    "trial_type": "pl_back",
    "target": "sóletok",
    "prompt": "Ez egy sólet. Ezek itt sóletok.",
    "stimulus": "<p style=\"font-size:48px;\">sóletok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "z": "",
    "trial_type": "pl_front",
    "target": "sóletek",
    "prompt": "Ez egy sólet. Ezek itt sóletek.",
    "stimulus": "<p style=\"font-size:48px;\">sóletek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "z": "",
    "trial_type": "ine_back",
    "target": "sóletban",
    "prompt": "Ez egy sólet. Bízom a sóletban.",
    "stimulus": "<p style=\"font-size:48px;\">sóletban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sólet",
    "back": 86,
    "front": 1280,
    "log_odds_back": -2.7003,
    "stem_freq": 1366,
    "language": "yi",
    "transcription": "šólet",
    "z": "",
    "trial_type": "ine_front",
    "target": "sóletben",
    "prompt": "Ez egy sólet. Bízom a sóletben.",
    "stimulus": "<p style=\"font-size:48px;\">sóletben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "z": "",
    "trial_type": "pl_back",
    "target": "vamzerok",
    "prompt": "Ez egy vamzer. Ezek itt vamzerok.",
    "stimulus": "<p style=\"font-size:48px;\">vamzerok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "z": "",
    "trial_type": "pl_front",
    "target": "vamzerek",
    "prompt": "Ez egy vamzer. Ezek itt vamzerek.",
    "stimulus": "<p style=\"font-size:48px;\">vamzerek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "z": "",
    "trial_type": "ine_back",
    "target": "vamzerban",
    "prompt": "Ez egy vamzer. Bízom a vamzerban.",
    "stimulus": "<p style=\"font-size:48px;\">vamzerban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "vamzer",
    "back": 9,
    "front": 107,
    "log_odds_back": -2.4756,
    "stem_freq": 116,
    "language": "yi",
    "transcription": "vamzer",
    "z": "",
    "trial_type": "ine_front",
    "target": "vamzerben",
    "prompt": "Ez egy vamzer. Bízom a vamzerben.",
    "stimulus": "<p style=\"font-size:48px;\">vamzerben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "z": "",
    "trial_type": "pl_back",
    "target": "váteszok",
    "prompt": "Ez egy vátesz. Ezek itt váteszok.",
    "stimulus": "<p style=\"font-size:48px;\">váteszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "z": "",
    "trial_type": "pl_front",
    "target": "váteszek",
    "prompt": "Ez egy vátesz. Ezek itt váteszek.",
    "stimulus": "<p style=\"font-size:48px;\">váteszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "z": "",
    "trial_type": "ine_back",
    "target": "váteszban",
    "prompt": "Ez egy vátesz. Bízom a váteszban.",
    "stimulus": "<p style=\"font-size:48px;\">váteszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "vátesz",
    "back": 1,
    "front": 737,
    "log_odds_back": -6.6026,
    "stem_freq": 738,
    "language": "la",
    "transcription": "vátes",
    "z": "",
    "trial_type": "ine_front",
    "target": "váteszben",
    "prompt": "Ez egy vátesz. Bízom a váteszben.",
    "stimulus": "<p style=\"font-size:48px;\">váteszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "z": "",
    "trial_type": "pl_back",
    "target": "zacsekok",
    "prompt": "Ez egy zacsek. Ezek itt zacsekok.",
    "stimulus": "<p style=\"font-size:48px;\">zacsekok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "z": "",
    "trial_type": "pl_front",
    "target": "zacsekek",
    "prompt": "Ez egy zacsek. Ezek itt zacsekek.",
    "stimulus": "<p style=\"font-size:48px;\">zacsekek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "z": "",
    "trial_type": "ine_back",
    "target": "zacsekban",
    "prompt": "Ez egy zacsek. Bízom a zacsekban.",
    "stimulus": "<p style=\"font-size:48px;\">zacsekban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "zacsek",
    "back": 59,
    "front": 12,
    "log_odds_back": 1.5926,
    "stem_freq": 71,
    "language": "yi",
    "transcription": "začek",
    "z": "",
    "trial_type": "ine_front",
    "target": "zacsekben",
    "prompt": "Ez egy zacsek. Bízom a zacsekben.",
    "stimulus": "<p style=\"font-size:48px;\">zacsekben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "z": "z",
    "trial_type": "pl_back",
    "target": "ágensok",
    "prompt": "Ez egy ágens. Ezek itt ágensok.",
    "stimulus": "<p style=\"font-size:48px;\">ágensok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "z": "z",
    "trial_type": "pl_front",
    "target": "ágensek",
    "prompt": "Ez egy ágens. Ezek itt ágensek.",
    "stimulus": "<p style=\"font-size:48px;\">ágensek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "z": "z",
    "trial_type": "ine_back",
    "target": "ágensban",
    "prompt": "Ez egy ágens. Bízom az ágensban.",
    "stimulus": "<p style=\"font-size:48px;\">ágensban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ágens",
    "back": 7,
    "front": 7110,
    "log_odds_back": -6.9233,
    "stem_freq": 7117,
    "language": "la",
    "transcription": "ágenš",
    "z": "z",
    "trial_type": "ine_front",
    "target": "ágensben",
    "prompt": "Ez egy ágens. Bízom az ágensben.",
    "stimulus": "<p style=\"font-size:48px;\">ágensben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "z": "z",
    "trial_type": "pl_back",
    "target": "ájerok",
    "prompt": "Ez egy ájer. Ezek itt ájerok.",
    "stimulus": "<p style=\"font-size:48px;\">ájerok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "z": "z",
    "trial_type": "pl_front",
    "target": "ájerek",
    "prompt": "Ez egy ájer. Ezek itt ájerek.",
    "stimulus": "<p style=\"font-size:48px;\">ájerek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "z": "z",
    "trial_type": "ine_back",
    "target": "ájerban",
    "prompt": "Ez egy ájer. Bízom az ájerban.",
    "stimulus": "<p style=\"font-size:48px;\">ájerban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ájer",
    "back": 15,
    "front": 67,
    "log_odds_back": -1.4966,
    "stem_freq": 82,
    "language": "yi",
    "transcription": "ájer",
    "z": "z",
    "trial_type": "ine_front",
    "target": "ájerben",
    "prompt": "Ez egy ájer. Bízom az ájerben.",
    "stimulus": "<p style=\"font-size:48px;\">ájerben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "z": "z",
    "trial_type": "pl_back",
    "target": "ómenok",
    "prompt": "Ez egy ómen. Ezek itt ómenok.",
    "stimulus": "<p style=\"font-size:48px;\">ómenok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "z": "z",
    "trial_type": "pl_front",
    "target": "ómenek",
    "prompt": "Ez egy ómen. Ezek itt ómenek.",
    "stimulus": "<p style=\"font-size:48px;\">ómenek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "z": "z",
    "trial_type": "ine_back",
    "target": "ómenban",
    "prompt": "Ez egy ómen. Bízom az ómenban.",
    "stimulus": "<p style=\"font-size:48px;\">ómenban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "ómen",
    "back": 2,
    "front": 996,
    "log_odds_back": -6.2106,
    "stem_freq": 998,
    "language": "la",
    "transcription": "ómen",
    "z": "z",
    "trial_type": "ine_front",
    "target": "ómenben",
    "prompt": "Ez egy ómen. Bízom az ómenben.",
    "stimulus": "<p style=\"font-size:48px;\">ómenben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "transcription": "bakter",
    "z": "",
    "trial_type": "pl_back",
    "target": "bakterok",
    "prompt": "Ez egy bakter. Ezek itt bakterok.",
    "stimulus": "<p style=\"font-size:48px;\">bakterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "transcription": "bakter",
    "z": "",
    "trial_type": "pl_front",
    "target": "bakterek",
    "prompt": "Ez egy bakter. Ezek itt bakterek.",
    "stimulus": "<p style=\"font-size:48px;\">bakterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "transcription": "bakter",
    "z": "",
    "trial_type": "ine_back",
    "target": "bakterban",
    "prompt": "Ez egy bakter. Bízom a bakterban.",
    "stimulus": "<p style=\"font-size:48px;\">bakterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "bakter",
    "back": 366,
    "front": 268,
    "log_odds_back": 0.3116,
    "stem_freq": 634,
    "language": "de",
    "transcription": "bakter",
    "z": "",
    "trial_type": "ine_front",
    "target": "bakterben",
    "prompt": "Ez egy bakter. Bízom a bakterben.",
    "stimulus": "<p style=\"font-size:48px;\">bakterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "transcription": "flanel",
    "z": "",
    "trial_type": "pl_back",
    "target": "flanelok",
    "prompt": "Ez egy flanel. Ezek itt flanelok.",
    "stimulus": "<p style=\"font-size:48px;\">flanelok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "transcription": "flanel",
    "z": "",
    "trial_type": "pl_front",
    "target": "flanelek",
    "prompt": "Ez egy flanel. Ezek itt flanelek.",
    "stimulus": "<p style=\"font-size:48px;\">flanelek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "transcription": "flanel",
    "z": "",
    "trial_type": "ine_back",
    "target": "flanelban",
    "prompt": "Ez egy flanel. Bízom a flanelban.",
    "stimulus": "<p style=\"font-size:48px;\">flanelban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "flanel",
    "back": 73,
    "front": 159,
    "log_odds_back": -0.7784,
    "stem_freq": 232,
    "language": "fr",
    "transcription": "flanel",
    "z": "",
    "trial_type": "ine_front",
    "target": "flanelben",
    "prompt": "Ez egy flanel. Bízom a flanelben.",
    "stimulus": "<p style=\"font-size:48px;\">flanelben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "transcription": "fotel",
    "z": "",
    "trial_type": "pl_back",
    "target": "fotelok",
    "prompt": "Ez egy fotel. Ezek itt fotelok.",
    "stimulus": "<p style=\"font-size:48px;\">fotelok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "transcription": "fotel",
    "z": "",
    "trial_type": "pl_front",
    "target": "fotelek",
    "prompt": "Ez egy fotel. Ezek itt fotelek.",
    "stimulus": "<p style=\"font-size:48px;\">fotelek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "transcription": "fotel",
    "z": "",
    "trial_type": "ine_back",
    "target": "fotelban",
    "prompt": "Ez egy fotel. Bízom a fotelban.",
    "stimulus": "<p style=\"font-size:48px;\">fotelban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "fotel",
    "back": 11597,
    "front": 25177,
    "log_odds_back": -0.7752,
    "stem_freq": 36774,
    "language": "fr",
    "transcription": "fotel",
    "z": "",
    "trial_type": "ine_front",
    "target": "fotelben",
    "prompt": "Ez egy fotel. Bízom a fotelben.",
    "stimulus": "<p style=\"font-size:48px;\">fotelben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "gatyesz",
    "back": 22,
    "front": 9,
    "log_odds_back": 0.8938,
    "stem_freq": 31,
    "language": "hu",
    "transcription": "gaṯes",
    "z": "",
    "trial_type": "pl_back",
    "target": "gatyeszok",
    "prompt": "Ez egy gatyesz. Ezek itt gatyeszok.",
    "stimulus": "<p style=\"font-size:48px;\">gatyeszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "gatyesz",
    "back": 22,
    "front": 9,
    "log_odds_back": 0.8938,
    "stem_freq": 31,
    "language": "hu",
    "transcription": "gaṯes",
    "z": "",
    "trial_type": "pl_front",
    "target": "gatyeszek",
    "prompt": "Ez egy gatyesz. Ezek itt gatyeszek.",
    "stimulus": "<p style=\"font-size:48px;\">gatyeszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "gatyesz",
    "back": 22,
    "front": 9,
    "log_odds_back": 0.8938,
    "stem_freq": 31,
    "language": "hu",
    "transcription": "gaṯes",
    "z": "",
    "trial_type": "ine_back",
    "target": "gatyeszban",
    "prompt": "Ez egy gatyesz. Bízom a gatyeszban.",
    "stimulus": "<p style=\"font-size:48px;\">gatyeszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "gatyesz",
    "back": 22,
    "front": 9,
    "log_odds_back": 0.8938,
    "stem_freq": 31,
    "language": "hu",
    "transcription": "gaṯes",
    "z": "",
    "trial_type": "ine_front",
    "target": "gatyeszben",
    "prompt": "Ez egy gatyesz. Bízom a gatyeszben.",
    "stimulus": "<p style=\"font-size:48px;\">gatyeszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "transcription": "jampec",
    "z": "",
    "trial_type": "pl_back",
    "target": "jampecok",
    "prompt": "Ez egy jampec. Ezek itt jampecok.",
    "stimulus": "<p style=\"font-size:48px;\">jampecok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "transcription": "jampec",
    "z": "",
    "trial_type": "pl_front",
    "target": "jampecek",
    "prompt": "Ez egy jampec. Ezek itt jampecek.",
    "stimulus": "<p style=\"font-size:48px;\">jampecek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "transcription": "jampec",
    "z": "",
    "trial_type": "ine_back",
    "target": "jampecban",
    "prompt": "Ez egy jampec. Bízom a jampecban.",
    "stimulus": "<p style=\"font-size:48px;\">jampecban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "jampec",
    "back": 183,
    "front": 281,
    "log_odds_back": -0.4289,
    "stem_freq": 464,
    "language": "de",
    "transcription": "jampec",
    "z": "",
    "trial_type": "ine_front",
    "target": "jampecben",
    "prompt": "Ez egy jampec. Bízom a jampecben.",
    "stimulus": "<p style=\"font-size:48px;\">jampecben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kadet",
    "back": 158,
    "front": 416,
    "log_odds_back": -0.9681,
    "stem_freq": 574,
    "language": "fr",
    "transcription": "kadet",
    "z": "",
    "trial_type": "pl_back",
    "target": "kadetok",
    "prompt": "Ez egy kadet. Ezek itt kadetok.",
    "stimulus": "<p style=\"font-size:48px;\">kadetok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kadet",
    "back": 158,
    "front": 416,
    "log_odds_back": -0.9681,
    "stem_freq": 574,
    "language": "fr",
    "transcription": "kadet",
    "z": "",
    "trial_type": "pl_front",
    "target": "kadetek",
    "prompt": "Ez egy kadet. Ezek itt kadetek.",
    "stimulus": "<p style=\"font-size:48px;\">kadetek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kadet",
    "back": 158,
    "front": 416,
    "log_odds_back": -0.9681,
    "stem_freq": 574,
    "language": "fr",
    "transcription": "kadet",
    "z": "",
    "trial_type": "ine_back",
    "target": "kadetban",
    "prompt": "Ez egy kadet. Bízom a kadetban.",
    "stimulus": "<p style=\"font-size:48px;\">kadetban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kadet",
    "back": 158,
    "front": 416,
    "log_odds_back": -0.9681,
    "stem_freq": 574,
    "language": "fr",
    "transcription": "kadet",
    "z": "",
    "trial_type": "ine_front",
    "target": "kadetben",
    "prompt": "Ez egy kadet. Bízom a kadetben.",
    "stimulus": "<p style=\"font-size:48px;\">kadetben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "transcription": "karter",
    "z": "",
    "trial_type": "pl_back",
    "target": "karterok",
    "prompt": "Ez egy karter. Ezek itt karterok.",
    "stimulus": "<p style=\"font-size:48px;\">karterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "transcription": "karter",
    "z": "",
    "trial_type": "pl_front",
    "target": "karterek",
    "prompt": "Ez egy karter. Ezek itt karterek.",
    "stimulus": "<p style=\"font-size:48px;\">karterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "transcription": "karter",
    "z": "",
    "trial_type": "ine_back",
    "target": "karterban",
    "prompt": "Ez egy karter. Bízom a karterban.",
    "stimulus": "<p style=\"font-size:48px;\">karterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "karter",
    "back": 113,
    "front": 232,
    "log_odds_back": -0.7193,
    "stem_freq": 345,
    "language": "en",
    "transcription": "karter",
    "z": "",
    "trial_type": "ine_front",
    "target": "karterben",
    "prompt": "Ez egy karter. Bízom a karterben.",
    "stimulus": "<p style=\"font-size:48px;\">karterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "klapec",
    "back": 18,
    "front": 9,
    "log_odds_back": 0.6931,
    "stem_freq": 27,
    "language": "de",
    "transcription": "klapec",
    "z": "",
    "trial_type": "pl_back",
    "target": "klapecok",
    "prompt": "Ez egy klapec. Ezek itt klapecok.",
    "stimulus": "<p style=\"font-size:48px;\">klapecok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "klapec",
    "back": 18,
    "front": 9,
    "log_odds_back": 0.6931,
    "stem_freq": 27,
    "language": "de",
    "transcription": "klapec",
    "z": "",
    "trial_type": "pl_front",
    "target": "klapecek",
    "prompt": "Ez egy klapec. Ezek itt klapecek.",
    "stimulus": "<p style=\"font-size:48px;\">klapecek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "klapec",
    "back": 18,
    "front": 9,
    "log_odds_back": 0.6931,
    "stem_freq": 27,
    "language": "de",
    "transcription": "klapec",
    "z": "",
    "trial_type": "ine_back",
    "target": "klapecban",
    "prompt": "Ez egy klapec. Bízom a klapecban.",
    "stimulus": "<p style=\"font-size:48px;\">klapecban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "klapec",
    "back": 18,
    "front": 9,
    "log_odds_back": 0.6931,
    "stem_freq": 27,
    "language": "de",
    "transcription": "klapec",
    "z": "",
    "trial_type": "ine_front",
    "target": "klapecben",
    "prompt": "Ez egy klapec. Bízom a klapecben.",
    "stimulus": "<p style=\"font-size:48px;\">klapecben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "transcription": "klozet",
    "z": "",
    "trial_type": "pl_back",
    "target": "klozetok",
    "prompt": "Ez egy klozet. Ezek itt klozetok.",
    "stimulus": "<p style=\"font-size:48px;\">klozetok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "transcription": "klozet",
    "z": "",
    "trial_type": "pl_front",
    "target": "klozetek",
    "prompt": "Ez egy klozet. Ezek itt klozetek.",
    "stimulus": "<p style=\"font-size:48px;\">klozetek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "transcription": "klozet",
    "z": "",
    "trial_type": "ine_back",
    "target": "klozetban",
    "prompt": "Ez egy klozet. Bízom a klozetban.",
    "stimulus": "<p style=\"font-size:48px;\">klozetban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "klozet",
    "back": 388,
    "front": 185,
    "log_odds_back": 0.7406,
    "stem_freq": 573,
    "language": "fr",
    "transcription": "klozet",
    "z": "",
    "trial_type": "ine_front",
    "target": "klozetben",
    "prompt": "Ez egy klozet. Bízom a klozetben.",
    "stimulus": "<p style=\"font-size:48px;\">klozetben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "transcription": "koles",
    "z": "",
    "trial_type": "pl_back",
    "target": "koleszok",
    "prompt": "Ez egy kolesz. Ezek itt koleszok.",
    "stimulus": "<p style=\"font-size:48px;\">koleszok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "transcription": "koles",
    "z": "",
    "trial_type": "pl_front",
    "target": "koleszek",
    "prompt": "Ez egy kolesz. Ezek itt koleszek.",
    "stimulus": "<p style=\"font-size:48px;\">koleszek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "transcription": "koles",
    "z": "",
    "trial_type": "ine_back",
    "target": "koleszban",
    "prompt": "Ez egy kolesz. Bízom a koleszban.",
    "stimulus": "<p style=\"font-size:48px;\">koleszban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kolesz",
    "back": 2920,
    "front": 320,
    "log_odds_back": 2.211,
    "stem_freq": 3240,
    "language": "hu",
    "transcription": "koles",
    "z": "",
    "trial_type": "ine_front",
    "target": "koleszben",
    "prompt": "Ez egy kolesz. Bízom a koleszben.",
    "stimulus": "<p style=\"font-size:48px;\">koleszben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "transcription": "krapek",
    "z": "",
    "trial_type": "pl_back",
    "target": "krapekok",
    "prompt": "Ez egy krapek. Ezek itt krapekok.",
    "stimulus": "<p style=\"font-size:48px;\">krapekok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "transcription": "krapek",
    "z": "",
    "trial_type": "pl_front",
    "target": "krapekek",
    "prompt": "Ez egy krapek. Ezek itt krapekek.",
    "stimulus": "<p style=\"font-size:48px;\">krapekek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "transcription": "krapek",
    "z": "",
    "trial_type": "ine_back",
    "target": "krapekban",
    "prompt": "Ez egy krapek. Bízom a krapekban.",
    "stimulus": "<p style=\"font-size:48px;\">krapekban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "krapek",
    "back": 436,
    "front": 39,
    "log_odds_back": 2.4141,
    "stem_freq": 475,
    "language": "de",
    "transcription": "krapek",
    "z": "",
    "trial_type": "ine_front",
    "target": "krapekben",
    "prompt": "Ez egy krapek. Bízom a krapekben.",
    "stimulus": "<p style=\"font-size:48px;\">krapekben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "transcription": "kóter",
    "z": "",
    "trial_type": "pl_back",
    "target": "kóterok",
    "prompt": "Ez egy kóter. Ezek itt kóterok.",
    "stimulus": "<p style=\"font-size:48px;\">kóterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "transcription": "kóter",
    "z": "",
    "trial_type": "pl_front",
    "target": "kóterek",
    "prompt": "Ez egy kóter. Ezek itt kóterek.",
    "stimulus": "<p style=\"font-size:48px;\">kóterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "transcription": "kóter",
    "z": "",
    "trial_type": "ine_back",
    "target": "kóterban",
    "prompt": "Ez egy kóter. Bízom a kóterban.",
    "stimulus": "<p style=\"font-size:48px;\">kóterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "kóter",
    "back": 222,
    "front": 254,
    "log_odds_back": -0.1347,
    "stem_freq": 476,
    "language": "de",
    "transcription": "kóter",
    "z": "",
    "trial_type": "ine_front",
    "target": "kóterben",
    "prompt": "Ez egy kóter. Bízom a kóterben.",
    "stimulus": "<p style=\"font-size:48px;\">kóterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "transcription": "malter",
    "z": "",
    "trial_type": "pl_back",
    "target": "malterok",
    "prompt": "Ez egy malter. Ezek itt malterok.",
    "stimulus": "<p style=\"font-size:48px;\">malterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "transcription": "malter",
    "z": "",
    "trial_type": "pl_front",
    "target": "malterek",
    "prompt": "Ez egy malter. Ezek itt malterek.",
    "stimulus": "<p style=\"font-size:48px;\">malterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "transcription": "malter",
    "z": "",
    "trial_type": "ine_back",
    "target": "malterban",
    "prompt": "Ez egy malter. Bízom a malterban.",
    "stimulus": "<p style=\"font-size:48px;\">malterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "malter",
    "back": 667,
    "front": 222,
    "log_odds_back": 1.1001,
    "stem_freq": 889,
    "language": "de",
    "transcription": "malter",
    "z": "",
    "trial_type": "ine_front",
    "target": "malterben",
    "prompt": "Ez egy malter. Bízom a malterben.",
    "stimulus": "<p style=\"font-size:48px;\">malterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "transcription": "matek",
    "z": "",
    "trial_type": "pl_back",
    "target": "matekok",
    "prompt": "Ez egy matek. Ezek itt matekok.",
    "stimulus": "<p style=\"font-size:48px;\">matekok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "transcription": "matek",
    "z": "",
    "trial_type": "pl_front",
    "target": "matekek",
    "prompt": "Ez egy matek. Ezek itt matekek.",
    "stimulus": "<p style=\"font-size:48px;\">matekek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "transcription": "matek",
    "z": "",
    "trial_type": "ine_back",
    "target": "matekban",
    "prompt": "Ez egy matek. Bízom a matekban.",
    "stimulus": "<p style=\"font-size:48px;\">matekban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "matek",
    "back": 18299,
    "front": 276,
    "log_odds_back": 4.1942,
    "stem_freq": 18575,
    "language": "en",
    "transcription": "matek",
    "z": "",
    "trial_type": "ine_front",
    "target": "matekben",
    "prompt": "Ez egy matek. Bízom a matekben.",
    "stimulus": "<p style=\"font-size:48px;\">matekben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "mutter",
    "back": 222,
    "front": 107,
    "log_odds_back": 0.7298,
    "stem_freq": 329,
    "language": "de",
    "transcription": "mutter",
    "z": "",
    "trial_type": "pl_back",
    "target": "mutterok",
    "prompt": "Ez egy mutter. Ezek itt mutterok.",
    "stimulus": "<p style=\"font-size:48px;\">mutterok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "mutter",
    "back": 222,
    "front": 107,
    "log_odds_back": 0.7298,
    "stem_freq": 329,
    "language": "de",
    "transcription": "mutter",
    "z": "",
    "trial_type": "pl_front",
    "target": "mutterek",
    "prompt": "Ez egy mutter. Ezek itt mutterek.",
    "stimulus": "<p style=\"font-size:48px;\">mutterek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "mutter",
    "back": 222,
    "front": 107,
    "log_odds_back": 0.7298,
    "stem_freq": 329,
    "language": "de",
    "transcription": "mutter",
    "z": "",
    "trial_type": "ine_back",
    "target": "mutterban",
    "prompt": "Ez egy mutter. Bízom a mutterban.",
    "stimulus": "<p style=\"font-size:48px;\">mutterban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "mutter",
    "back": 222,
    "front": 107,
    "log_odds_back": 0.7298,
    "stem_freq": 329,
    "language": "de",
    "transcription": "mutter",
    "z": "",
    "trial_type": "ine_front",
    "target": "mutterben",
    "prompt": "Ez egy mutter. Bízom a mutterben.",
    "stimulus": "<p style=\"font-size:48px;\">mutterben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "prakker",
    "back": 32,
    "front": 40,
    "log_odds_back": -0.2231,
    "stem_freq": 72,
    "language": "de",
    "transcription": "prakker",
    "z": "",
    "trial_type": "pl_back",
    "target": "prakkerok",
    "prompt": "Ez egy prakker. Ezek itt prakkerok.",
    "stimulus": "<p style=\"font-size:48px;\">prakkerok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "prakker",
    "back": 32,
    "front": 40,
    "log_odds_back": -0.2231,
    "stem_freq": 72,
    "language": "de",
    "transcription": "prakker",
    "z": "",
    "trial_type": "pl_front",
    "target": "prakkerek",
    "prompt": "Ez egy prakker. Ezek itt prakkerek.",
    "stimulus": "<p style=\"font-size:48px;\">prakkerek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "prakker",
    "back": 32,
    "front": 40,
    "log_odds_back": -0.2231,
    "stem_freq": 72,
    "language": "de",
    "transcription": "prakker",
    "z": "",
    "trial_type": "ine_back",
    "target": "prakkerban",
    "prompt": "Ez egy prakker. Bízom a prakkerban.",
    "stimulus": "<p style=\"font-size:48px;\">prakkerban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "prakker",
    "back": 32,
    "front": 40,
    "log_odds_back": -0.2231,
    "stem_freq": 72,
    "language": "de",
    "transcription": "prakker",
    "z": "",
    "trial_type": "ine_front",
    "target": "prakkerben",
    "prompt": "Ez egy prakker. Bízom a prakkerben.",
    "stimulus": "<p style=\"font-size:48px;\">prakkerben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "transcription": "šumer",
    "z": "",
    "trial_type": "pl_back",
    "target": "sumerok",
    "prompt": "Ez egy sumer. Ezek itt sumerok.",
    "stimulus": "<p style=\"font-size:48px;\">sumerok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "transcription": "šumer",
    "z": "",
    "trial_type": "pl_front",
    "target": "sumerek",
    "prompt": "Ez egy sumer. Ezek itt sumerek.",
    "stimulus": "<p style=\"font-size:48px;\">sumerek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "transcription": "šumer",
    "z": "",
    "trial_type": "ine_back",
    "target": "sumerban",
    "prompt": "Ez egy sumer. Bízom a sumerban.",
    "stimulus": "<p style=\"font-size:48px;\">sumerban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "sumer",
    "back": 985,
    "front": 684,
    "log_odds_back": 0.3647,
    "stem_freq": 1669,
    "language": "akk",
    "transcription": "šumer",
    "z": "",
    "trial_type": "ine_front",
    "target": "sumerben",
    "prompt": "Ez egy sumer. Bízom a sumerben.",
    "stimulus": "<p style=\"font-size:48px;\">sumerben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "transcription": "skander",
    "z": "",
    "trial_type": "pl_back",
    "target": "szkanderok",
    "prompt": "Ez egy szkander. Ezek itt szkanderok.",
    "stimulus": "<p style=\"font-size:48px;\">szkanderok<\/p>",
    "trial_front": false,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "transcription": "skander",
    "z": "",
    "trial_type": "pl_front",
    "target": "szkanderek",
    "prompt": "Ez egy szkander. Ezek itt szkanderek.",
    "stimulus": "<p style=\"font-size:48px;\">szkanderek<\/p>",
    "trial_front": true,
    "trial_pl": true,
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "transcription": "skander",
    "z": "",
    "trial_type": "ine_back",
    "target": "szkanderban",
    "prompt": "Ez egy szkander. Bízom a szkanderban.",
    "stimulus": "<p style=\"font-size:48px;\">szkanderban<\/p>",
    "trial_front": false,
    "trial_pl": false,
    "choices": ["f", "j"]
  },
  {
    "stem": "szkander",
    "back": 139,
    "front": 375,
    "log_odds_back": -0.9925,
    "stem_freq": 514,
    "language": "ar",
    "transcription": "skander",
    "z": "",
    "trial_type": "ine_front",
    "target": "szkanderben",
    "prompt": "Ez egy szkander. Bízom a szkanderben.",
    "stimulus": "<p style=\"font-size:48px;\">szkanderben<\/p>",
    "trial_front": true,
    "trial_pl": false,
    "choices": ["f", "j"]
  }
]
